INSERT INTO "gui_elements" VALUES (341, 'axbuttonbotóncalendarhoy', '', 'Calendar', 'com.apple.iCal', 'Ir a hoy', '', 'Visualización', 'Command T', 13, 35);
INSERT INTO "gui_elements" VALUES (342, 'axbuttonbuttonsafariclicktoclosethistab;option-clicktoclosealltabsexceptthisoneclosetab', '', 'Safari', 'com.apple.Safari', 'Close Tab', 'Click to close this tab; Option-click to close all tabs except this one', 'Edit', 'Command W', 20, 24);
INSERT INTO "gui_elements" VALUES (343, 'axtextfieldsearchtextfieldsafariaxsearchfield', 'axtextfieldsearchtextfield_ns:28', 'Safari', 'com.apple.Safari', 'Find', '', 'Find', 'Command F', 20, 42);
INSERT INTO "gui_elements" VALUES (344, 'axbuttonbuttonsafariclicktoclosethistabclosetab', '', 'Safari', 'com.apple.Safari', 'Close Tab', 'Click to close this tab', 'Edit', 'Command W', 20, 24);
INSERT INTO "gui_elements" VALUES (345, 'axbuttonbuttonmaildelete', '', 'Mail', 'com.apple.mail', 'Delete', '', 'Edit', 'Command Delete', 18, 37);
INSERT INTO "gui_elements" VALUES (346, 'axbuttonbuttonmailjunk', '', 'Mail', 'com.apple.mail', 'As Junk Mail', 'Mark/Unmark as Junk Mail', 'Mark', 'Command Shift U', 18, 100);
INSERT INTO "gui_elements" VALUES (347, 'axbuttonbuttonmailreply', '', 'Mail', 'com.apple.mail', 'Reply', '', 'Message', 'Command R', 18, 34);
INSERT INTO "gui_elements" VALUES (348, 'axbuttonbuttonmailforward', '', 'Mail', 'com.apple.mail', 'Forward', '', 'Message', 'Command Shift F', 18, 91);
INSERT INTO "gui_elements" VALUES (349, 'axbuttonbuttonmailsmallerdecreasefontsizeforselectedmessage', '', 'Mail', 'com.apple.mail', 'Smaller', 'Decrease font size for selected message', 'Style', 'Command -', 18, 117);
INSERT INTO "gui_elements" VALUES (350, 'axbuttonbuttonmailbiggerincreasefontsizeforselectedmessage', '', 'Mail', 'com.apple.mail', 'Bigger', 'Increase font size for selected message', 'Style', 'Command +', 18, 116);
INSERT INTO "gui_elements" VALUES (351, 'axbuttonbotóndecierremail', '', 'Mail', 'com.apple.mail', 'Cerrar', '', 'Archivo', 'Command W', 18, 24);
INSERT INTO "gui_elements" VALUES (352, 'axbuttonbotóndeminimizaciónmail', '', 'Mail', 'com.apple.mail', 'Minimizar', '', 'Ventana', 'Command M', 18, 103);
INSERT INTO "gui_elements" VALUES (353, 'axbuttonbotónmailrecibir', '', 'Mail', 'com.apple.mail', 'Descargar todo el correo nuevo', '', 'Buzón', 'Command Shift N', 18, 17);
INSERT INTO "gui_elements" VALUES (354, 'axbuttonbotónmailmensajenuevo', '', 'Mail', 'com.apple.mail', 'Mensaje nuevo', '', 'Archivo', 'Command N', 18, 16);
INSERT INTO "gui_elements" VALUES (355, 'axbuttonbotónmaileliminareliminarlosmensajesseleccionados', '', 'Mail', 'com.apple.mail', 'Eliminar', 'Eliminar los mensajes seleccionados', 'Edición', 'Command Delete', 18, 37);
INSERT INTO "gui_elements" VALUES (356, 'axbuttonbotónmailnodeseadomarcarlosmensajesseleccionadoscomonodeseados', '', 'Mail', 'com.apple.mail', 'Como correo no deseado', 'Marcar los mensajes seleccionados como no deseados', 'Marcar', 'Command Shift J', 18, 145);
INSERT INTO "gui_elements" VALUES (357, 'axbuttonbotónmailnodeseadoaceptarlosmensajesseleccionados', '', 'Mail', 'com.apple.mail', 'Como correo deseado', 'Aceptar los mensajes seleccionados', 'Marcar', 'Command Shift J', 18, 145);
INSERT INTO "gui_elements" VALUES (358, 'axbuttonbotónmaileliminar', '', 'Mail', 'com.apple.mail', 'Eliminar', '', 'Edición', 'Command Delete', 18, 37);
INSERT INTO "gui_elements" VALUES (359, 'axbuttonbotónmailnodeseado', '', 'Mail', 'com.apple.mail', 'Como correo no deseado', '', 'Marcar', 'Command Shift J', 18, 145);
INSERT INTO "gui_elements" VALUES (360, 'axbuttonbotónmailresponderresponderalremitentedelmensajeseleccionado', '', 'Mail', 'com.apple.mail', 'Responder', 'Responder al remitente del mensaje seleccionado', 'Mensaje', 'Command R', 18, 34);
INSERT INTO "gui_elements" VALUES (361, 'axbuttonbotónmailresp.atodosresponderatodoslosremitentesdelmensajeseleccionado', '', 'Mail', 'com.apple.mail', 'Responder a todos', 'Responder a todos los remitentes del mensaje seleccionado', 'Mensaje', 'Command Shift R', 18, 97);
INSERT INTO "gui_elements" VALUES (362, 'axbuttonbotónmailreenviarreenviarlosmensajesseleccionados', '', 'Mail', 'com.apple.mail', 'Reenviar', 'Reenviar los mensajes seleccionados', 'Mensaje', 'Command Shift F', 18, 91);
INSERT INTO "gui_elements" VALUES (363, 'axbuttonbotónmailresponder', '', 'Mail', 'com.apple.mail', 'Responder', '', 'Mensaje', 'Command R', 18, 34);
INSERT INTO "gui_elements" VALUES (364, 'axbuttonbotónmailresp.atodos', '', 'Mail', 'com.apple.mail', 'Responder a todos', '', 'Mensaje', 'Command Shift R', 18, 97);
INSERT INTO "gui_elements" VALUES (365, 'axbuttonbotónmailreenviar', '', 'Mail', 'com.apple.mail', 'Reenviar', '', 'Mensaje', 'Command Shift F', 18, 91);
INSERT INTO "gui_elements" VALUES (366, 'axbuttonbotónmailañadirindicadorared', '', 'Mail', 'com.apple.mail', 'Red', '', 'Indicador', 'Command Shift L', 18, 13);
INSERT INTO "gui_elements" VALUES (367, 'axbuttonbotónmaileliminarindicadordered', '', 'Mail', 'com.apple.mail', 'Red', '', 'Indicador', 'Command Shift L', 18, 13);
INSERT INTO "gui_elements" VALUES (368, 'axbuttonbotónmailarchivar', '', 'Mail', 'com.apple.mail', 'Archivar', '', 'Mensaje', 'Command Control A', 18, 180);
INSERT INTO "gui_elements" VALUES (369, 'axbuttonbotónmailbarralateral', '', 'Mail', 'com.apple.mail', 'Ocultar lista de buzones', 'Mostrar/Ocultar lista de buzones', 'Visualización', 'Command Shift M', 18, 135);
INSERT INTO "gui_elements" VALUES (370, 'axbuttonbotónmailimprimir', '', 'Mail', 'com.apple.mail', 'Imprimir', '', 'Archivo', 'Command P', 18, 23);
INSERT INTO "gui_elements" VALUES (371, 'axbuttonbotónmailnoleídomarcarlosmensajesseleccionadoscomonoleídos', '', 'Mail', 'com.apple.mail', 'Como no leído', 'Marcar los mensajes seleccionados como no leídos', 'Marcar', 'Command Shift U', 18, 100);
INSERT INTO "gui_elements" VALUES (372, 'axbuttonbotónmailleídomarcarlosmensajesseleccionadoscomoleídos', '', 'Mail', 'com.apple.mail', 'Como leído', 'Marcar los mensajes seleccionados como leídos', 'Marcar', 'Command Shift U', 18, 100);
INSERT INTO "gui_elements" VALUES (373, 'axbuttonbotónmailagenda', '', 'Mail', 'com.apple.mail', 'Panel de Agenda', '', 'Ventana', 'Command Shift A', 18, 99);
INSERT INTO "gui_elements" VALUES (374, 'axbuttonbotónmailmáspequeñoreducireltamañodeletradelmensajeseleccionado', '', 'Mail', 'com.apple.mail', 'Más pequeño', 'Reducir el tamaño de letra del mensaje seleccionado', 'Estilo', 'Command -', 18, 117);
INSERT INTO "gui_elements" VALUES (375, 'axbuttonbotónmailmásgrandeaumentareltamañodeletradelmensajeseleccionado', '', 'Mail', 'com.apple.mail', 'Más grande', 'Aumentar el tamaño de letra del mensaje seleccionado', 'Estilo', 'Command +', 18, 116);
INSERT INTO "gui_elements" VALUES (376, 'axbuttonbotónmailañadirremitente', '', 'Mail', 'com.apple.mail', 'Añadir remitente a Contactos', '', 'Mensaje', 'Command Shift Y', 18, 11);
INSERT INTO "gui_elements" VALUES (377, 'axtextfieldcampodetextodebúsquedamailbuscaraxsearchfield', '', 'Mail', 'com.apple.mail', 'Búsqueda en buzón', '', 'Buscar', 'Command Option F', 18, 44);
INSERT INTO "gui_elements" VALUES (378, 'axbuttonbotónmailocultarlistadebuzonesocultar', '', 'Mail', 'com.apple.mail', 'Ocultar lista de buzones', '', 'Visualización', 'Command Shift M', 18, 135);
INSERT INTO "gui_elements" VALUES (379, 'axtextfieldtextfieldbaseocultarlistadebuzonesocultarlistadebuzones', '', 'Base', 'uk.co.menial.Base', 'Mostrar lista de buzones', '', 'Visualización', 'Command Shift M', 11, 135);
INSERT INTO "gui_elements" VALUES (380, 'axbuttonbotónmailmostrarlistadebuzonesmostrar', '', 'Mail', 'com.apple.mail', 'Mostrar lista de buzones', '', 'Visualización', 'Command Shift M', 18, 135);
INSERT INTO "gui_elements" VALUES (381, 'axcheckboxcasilladeverificaciónmailentrada', '', 'Mail', 'com.apple.mail', 'Entrada', '', 'Ir al buzón favorito', 'Command 1', 18, 54);
INSERT INTO "gui_elements" VALUES (382, 'axcheckboxcasilladeverificaciónmailenviado', '', 'Mail', 'com.apple.mail', 'Enviado', '', 'Ir al buzón favorito', 'Command 2', 18, 55);
INSERT INTO "gui_elements" VALUES (383, 'axcheckboxcasilladeverificaciónmailconindicador', '', 'Mail', 'com.apple.mail', 'Indicadores', '', 'Ir al buzón favorito', 'Command 3', 18, 56);
INSERT INTO "gui_elements" VALUES (384, 'axtextfieldcampodetextomailbuzónentradaentrada', '', 'Mail', 'com.apple.mail', 'Entrada', '', 'Ir al buzón favorito', 'Command 1', 18, 54);
INSERT INTO "gui_elements" VALUES (385, 'axtextfieldcampodetextomailbuzónenviadoenviado', '', 'Mail', 'com.apple.mail', 'Enviado', '', 'Ir al buzón favorito', 'Command 2', 18, 55);
INSERT INTO "gui_elements" VALUES (386, 'axtextfieldcampodetextomailbuzónconindicadorconindicador', '', 'Mail', 'com.apple.mail', 'Indicadores', '', 'Ir al buzón favorito', 'Command 3', 18, 56);
INSERT INTO "gui_elements" VALUES (387, 'axbuttonbotónmailenviar', '', 'Mail', 'com.apple.mail', 'Enviar', '', 'Mensaje', 'Command Shift D', 18, 93);
INSERT INTO "gui_elements" VALUES (388, 'axbuttonbotónmailadjuntar', '', 'Mail', 'com.apple.mail', 'Adjuntar archivos', '', 'Archivo', 'Command Shift A', 18, 99);
INSERT INTO "gui_elements" VALUES (389, 'axcheckboxcasilladeverificaciónmailnegritatextoennegrita', '', 'Mail', 'com.apple.mail', 'Negrita', 'Texto en negrita', 'Estilo', 'Command B', 18, 114);
INSERT INTO "gui_elements" VALUES (390, 'axcheckboxcasilladeverificaciónmailponereltextoencursiva', '', 'Mail', 'com.apple.mail', 'Cursiva', 'Poner el texto en cursiva', 'Estilo', 'Command I', 18, 26);
INSERT INTO "gui_elements" VALUES (391, 'axcheckboxcasilladeverificaciónmailsubrayarsubrayareltexto', '', 'Mail', 'com.apple.mail', 'Subrayar', 'Subrayar el texto', 'Estilo', 'Command U', 18, 115);
INSERT INTO "gui_elements" VALUES (392, 'axbuttonbotónmailalineareltextoalaizquierda', '', 'Mail', 'com.apple.mail', 'Alinear a la izquierda', 'Alinear el texto a la izquierda', 'Alineación', 'Command {', 18, 119);
INSERT INTO "gui_elements" VALUES (393, 'axbuttonbotónmailcentrareltexto', '', 'Mail', 'com.apple.mail', 'Centrar', 'Centrar el texto', 'Alineación', 'Command |', 18, 120);
INSERT INTO "gui_elements" VALUES (394, 'axbuttonbotónmailalineareltextoaladerecha', '', 'Mail', 'com.apple.mail', 'Alinear a la derecha', 'Alinear el texto a la derecha', 'Alineación', 'Command }', 18, 121);
INSERT INTO "gui_elements" VALUES (395, 'axbuttonbotónparapantallacompletamail', '', 'Mail', 'com.apple.mail', 'Usar pantalla completa', '', 'Visualización', 'Command Control F', 18, 43);
