INSERT INTO "gui_elements" VALUES (1, 'axbuttonclosebuttonsafari', '', 'Safari', 'com.apple.Safari', 'Close Window', '', 'File', 'Command Shift W', 36, 132);
INSERT INTO "gui_elements" VALUES (2, 'axbuttonminimizebuttonsafari', '', 'Safari', 'com.apple.Safari', 'Minimize', '', 'Window', 'Command M', 36, 52);
INSERT INTO "gui_elements" VALUES (3, 'axbuttonfullscreenbuttonsafari', '', 'Safari', 'com.apple.Safari', 'Enter Full Screen', '', 'View', 'Command Control F', 36, 74);
INSERT INTO "gui_elements" VALUES (4, 'axtextfieldtextfieldsafariaddressandsearch', 'axtextfieldtextfieldaddressandsearchweb_browser_address_and_search_field', 'Safari', 'com.apple.Safari', 'Open Location', 'Type a word or phrase to search for, or a webpage address, title, or bookmark', 'File', 'Command L', 36, 65);
INSERT INTO "gui_elements" VALUES (5, 'axbuttonbuttonsafarireloadreloadthecurrentpage', '', 'Safari', 'com.apple.Safari', 'Reload Page', 'Reload the current page', 'View', 'Command R', 36, 68);
INSERT INTO "gui_elements" VALUES (6, 'axbuttonbuttonsafaristopstoploadingthispage', '', 'Safari', 'com.apple.Safari', 'Stop', 'Stop loading this page', 'View', 'Command .', 36, 215);
INSERT INTO "gui_elements" VALUES (7, 'axbuttonbuttonsafaritogglereaderreader', 'axbuttonbuttonreadertogglereader_ns:173', 'Safari', 'com.apple.Safari', 'Show Reader', 'Show/Hide Reader', 'View', 'Command Shift R', 36, 118);
INSERT INTO "gui_elements" VALUES (8, 'axbuttonbuttonsafarireadinglist', '', 'Safari', 'com.apple.Safari', 'Show Reading List', 'Show/Hide Reading List', 'View', 'Command Shift L', 36, 11);
INSERT INTO "gui_elements" VALUES (9, 'axbuttonbuttonsafariaddpage', '', 'Safari', 'com.apple.Safari', 'Add to Reading List', '', 'Bookmarks', 'Command Shift D', 36, 115);
INSERT INTO "gui_elements" VALUES (10, 'axbuttonbuttonsafaritopsites', '', 'Safari', 'com.apple.Safari', 'Show Top Sites', '', 'History', 'Command Option 1', 36, 82);
INSERT INTO "gui_elements" VALUES (11, 'axbuttonbuttonsafarihome', '', 'Safari', 'com.apple.Safari', 'Home', '', 'History', 'Command Shift H', 36, 117);
INSERT INTO "gui_elements" VALUES (12, 'axbuttonbuttonsafarinewtab', '', 'Safari', 'com.apple.Safari', 'New Tab', '', 'File', 'Command T', 36, 37);
INSERT INTO "gui_elements" VALUES (13, 'axbuttonbuttonsafarihistory', '', 'Safari', 'com.apple.Safari', 'Show All History', '', 'History', 'Command Option 2', 36, 83);
INSERT INTO "gui_elements" VALUES (14, 'axbuttonbuttonsafaribookmarks', '', 'Safari', 'com.apple.Safari', 'Show All Bookmarks', '', 'Bookmarks', 'Command Option B', 36, 233);
INSERT INTO "gui_elements" VALUES (15, 'axbuttonbuttonsafaribookmarksbar', '', 'Safari', 'com.apple.Safari', 'Hide Bookmarks Bar', 'Show/Hide Bookmarks Bar', 'View', 'Command Shift B', 36, 210);
INSERT INTO "gui_elements" VALUES (16, 'axbuttonbuttonsafarizoomoutzoomout', '', 'Safari', 'com.apple.Safari', 'Zoom Out', 'Zoom out', 'View', 'Command -', 36, 42);
INSERT INTO "gui_elements" VALUES (17, 'axbuttonbuttonsafarizoominzoomin', '', 'Safari', 'com.apple.Safari', 'Zoom In', 'Zoom in', 'View', 'Command +', 36, 41);
INSERT INTO "gui_elements" VALUES (18, 'axbuttonbuttonsafarimail', '', 'Safari', 'com.apple.Safari', 'Email Link to this Page', '', 'Share', 'Command Shift I', 36, 131);
INSERT INTO "gui_elements" VALUES (19, 'axbuttonbuttonsafariprint', '', 'Safari', 'com.apple.Safari', 'Print', '', 'File', 'Command P', 36, 22);
INSERT INTO "gui_elements" VALUES (20, 'axbuttonbuttonsafariwebinspector', '', 'Safari', 'com.apple.Safari', 'Show Web Inspector', 'Show/Hide Web Inspector', 'Develop', 'Command Option I', 36, 61);
INSERT INTO "gui_elements" VALUES (21, 'axbuttonbuttonsafaridownloads', '', 'Safari', 'com.apple.Safari', 'Show Downloads', '', 'View', 'Command Option L', 36, 116);
INSERT INTO "gui_elements" VALUES (22, 'axbuttonbuttonsafari1password1password', '', 'Safari', 'com.apple.Safari', '1Password', '1Password', 'View', 'Command \', 36, 224);
INSERT INTO "gui_elements" VALUES (23, 'axbuttonbuttonsafaribackshowthepreviouspage', '', 'Safari', 'com.apple.Safari', 'Back', 'Show the previous page', 'History', 'Command [', 36, 105);
INSERT INTO "gui_elements" VALUES (24, 'axbuttonbuttonsafariforwardshowthenextpage', '', 'Safari', 'com.apple.Safari', 'Forward', 'Show the next page', 'History', 'Command ]', 36, 106);
INSERT INTO "gui_elements" VALUES (25, 'axcheckboxcheckboxsafarishowreadinglistshowreadinglist', '', 'Safari', 'com.apple.Safari', 'Show Reading List', 'Show Reading List', 'View', 'Command Shift L', 36, 11);
INSERT INTO "gui_elements" VALUES (26, 'axcheckboxcheckboxsafarihidereadinglisthidereadinglist', '', 'Safari', 'com.apple.Safari', 'Hide Reading List', 'Hide Reading List', 'View', 'Command Shift L', 36, 11);
INSERT INTO "gui_elements" VALUES (27, 'axcheckboxcheckboxsafarishowbookmarksshowallbookmarks', 'axcheckboxcheckboxshowbookmarks_ns:25', 'Safari', 'com.apple.Safari', 'Show All Bookmarks', 'Show all bookmarks', 'Bookmarks', 'Command Option B', 36, 233);
INSERT INTO "gui_elements" VALUES (28, 'axcheckboxcheckboxsafarihidebookmarkshideallbookmarks', '', 'Safari', 'com.apple.Safari', 'Hide All Bookmarks', 'Hide all bookmarks', 'Bookmarks', 'Command Option B', 36, 233);
INSERT INTO "gui_elements" VALUES (29, 'axbuttonbuttonsafarishowtopsitesshowtopsites', '', 'Safari', 'com.apple.Safari', 'Show Top Sites', 'Show Top Sites', 'History', 'Command Option 1', 36, 82);
INSERT INTO "gui_elements" VALUES (31, 'axbuttonbuttonsafarishowalltabsshowalltabs', '', 'Safari', 'com.apple.Safari', 'Show All Tabs', 'Show all tabs', 'View', 'Command Shift \', 36, 252);
INSERT INTO "gui_elements" VALUES (32, 'axbuttonclosebuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Close Window', '', 'File', 'Command Shift W', 24, 132);
INSERT INTO "gui_elements" VALUES (33, 'axbuttonminimizebuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Minimize', '', 'Window', 'Command M', 24, 52);
INSERT INTO "gui_elements" VALUES (34, 'axbuttonfullscreenbuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Enter Full Screen', '', 'Window', 'Command Control F', 24, 74);
INSERT INTO "gui_elements" VALUES (35, 'axbuttonbuttonchromenewtabnewtab', 'axbuttonbutton_ns:20', 'Chrome', 'com.google.Chrome', 'New Tab', 'New tab', 'File', 'Command T', 24, 37);
INSERT INTO "gui_elements" VALUES (36, 'axbuttonbuttonchromeclose', 'axbuttonbuttonclose_ns:10', 'Chrome', 'com.google.Chrome', 'Close Tab', '', 'File', 'Command W', 24, 17);
INSERT INTO "gui_elements" VALUES (37, 'axbuttonbuttonchromebackclicktogoback,holdtoseehistory', 'axbuttonbuttonback_ns:10', 'Chrome', 'com.google.Chrome', 'Back', 'Click to go back, hold to see history', 'History', 'Command [', 24, 105);
INSERT INTO "gui_elements" VALUES (38, 'axbuttonbuttonchromeforwardclicktogoforward,holdtoseehistory', 'axbuttonbuttonforward_ns:32', 'Chrome', 'com.google.Chrome', 'Forward', 'Click to go forward, hold to see history', 'History', 'Command ]', 24, 106);
INSERT INTO "gui_elements" VALUES (39, 'axbuttonbuttonchromehomeopenthehomepage', 'axbuttonbuttonhome_ns:37', 'Chrome', 'com.google.Chrome', 'Home', 'Open the home page', 'History', 'Command Shift H', 24, 117);
INSERT INTO "gui_elements" VALUES (40, 'axbuttonbuttonchromereloadreloadthispage', 'axbuttonbuttonreload_ns:63', 'Chrome', 'com.google.Chrome', 'Reload Page', 'Reload this page', 'View', 'Command R', 24, 68);
INSERT INTO "gui_elements" VALUES (41, 'axbuttonbuttonchromereloadstoploadingthispage', '', 'Chrome', 'com.google.Chrome', 'Stop', 'Stop loading this page', 'View', 'Command .', 24, 215);
INSERT INTO "gui_elements" VALUES (42, 'axtextfieldtextfieldchromeaddress', 'axtextfieldtextfieldaddress_ns:44', 'Chrome', 'com.google.Chrome', 'Open Location', '', 'File', 'Command L', 24, 65);
INSERT INTO "gui_elements" VALUES (43, 'axbuttonbuttonchrome1password1password', '', 'Chrome', 'com.google.Chrome', '1Password', '1Password', 'View', 'Command \', 24, 224);
INSERT INTO "gui_elements" VALUES (44, 'axbuttonclosebuttonfinder', '', 'Finder', 'com.apple.finder', 'Close Window', '', 'File', 'Command W', 9, 17);
INSERT INTO "gui_elements" VALUES (45, 'axbuttonminimizebuttonfinder', '', 'Finder', 'com.apple.finder', 'Minimize', '', 'Window', 'Command M', 9, 52);
INSERT INTO "gui_elements" VALUES (46, 'axbuttonbuttonfindernewfoldercreateanewfolderinthecurrentlocation', '', 'Finder', 'com.apple.finder', 'New Folder', 'Create a new folder in the current location', 'File', 'Command Shift N', 9, 56);
INSERT INTO "gui_elements" VALUES (47, 'axbuttonbuttonfinderdeletemovetheselecteditemtothetrash', '', 'Finder', 'com.apple.finder', 'Move to Trash', 'Move the selected item to the Trash', 'File', 'Command Delete', 9, 70);
INSERT INTO "gui_elements" VALUES (48, 'axbuttonbuttonfinderconnectconnecttoaserver', '', 'Finder', 'com.apple.finder', 'Connect to Server', 'Connect to a server', 'Go', 'Command K', 9, 122);
INSERT INTO "gui_elements" VALUES (49, 'axbuttonbuttonfinderquicklookshowitemswithquicklookorasaninstantslideshow', '', 'Finder', 'com.apple.finder', 'Quick Look', 'Show items with Quick Look or as an instant slideshow', 'File', 'Command Y', 9, 66);
INSERT INTO "gui_elements" VALUES (50, 'axbuttonbuttonfindergetinfoseeinformationabouttheselectedfilesandfolders', '', 'Finder', 'com.apple.finder', 'Get Info', 'See information about the selected files and folders', 'File', 'Command I', 9, 39);
INSERT INTO "gui_elements" VALUES (51, 'axradiobuttonradiobuttonfindericonview', '', 'Finder', 'com.apple.finder', 'as Icons', '', 'View', 'Command 1', 9, 78);
INSERT INTO "gui_elements" VALUES (52, 'axradiobuttonradiobuttonfinderlistview', '', 'Finder', 'com.apple.finder', 'as List', '', 'View', 'Command 2', 9, 79);
INSERT INTO "gui_elements" VALUES (53, 'axradiobuttonradiobuttonfindercolumnview', '', 'Finder', 'com.apple.finder', 'as Columns', '', 'View', 'Command 3', 9, 80);
INSERT INTO "gui_elements" VALUES (54, 'axradiobuttonradiobuttonfindercoverflowview', '', 'Finder', 'com.apple.finder', 'as Cover Flow', '', 'View', 'Command 4', 9, 81);
INSERT INTO "gui_elements" VALUES (55, 'axbuttonbuttonfinderback', '', 'Finder', 'com.apple.finder', 'Back', '', 'Go', 'Command [', 9, 105);
INSERT INTO "gui_elements" VALUES (56, 'axbuttonbuttonfinderforward', '', 'Finder', 'com.apple.finder', 'Forward', '', 'Go', 'Command ]', 9, 106);
INSERT INTO "gui_elements" VALUES (57, 'axbuttonbuttonfinderejectejectdisksandunmountservers', '', 'Finder', 'com.apple.finder', 'Eject', 'Eject disks and unmount servers', 'File', 'Command E', 9, 32);
INSERT INTO "gui_elements" VALUES (58, 'axtextfieldsearchtextfieldfindersearchaxsearchfield', 'axtextfieldsearchtextfieldsearch_ns:125', 'Finder', 'com.apple.finder', 'Find', '', 'File', 'Command F', 9, 29);
INSERT INTO "gui_elements" VALUES (59, 'axbuttonbuttonsafarifindprevious', '', 'Safari', 'com.apple.Safari', 'Find Previous', '', 'File', 'Command Shift G', 36, 31);
INSERT INTO "gui_elements" VALUES (60, 'axbuttonbuttonsafarifindnext', '', 'Safari', 'com.apple.Safari', 'Find Next', '', 'Find', 'Command G', 36, 30);
INSERT INTO "gui_elements" VALUES (61, 'axstatictexttextfinderallmyfilesallmyfiles', '', 'Finder', 'com.apple.finder', 'All My Files', '', 'Go', 'Command Shift F', 9, 113);
INSERT INTO "gui_elements" VALUES (62, 'axstatictexttextfinderairdropairdrop', '', 'Finder', 'com.apple.finder', 'AirDrop', '', 'Go', 'Command Shift R', 9, 118);
INSERT INTO "gui_elements" VALUES (63, 'axstatictexttextfinderdesktopdesktop', '', 'Finder', 'com.apple.finder', 'Desktop', '', 'Go', 'Command Shift D', 9, 115);
INSERT INTO "gui_elements" VALUES (64, 'axstatictexttextfinderhomehome', '', 'Finder', 'com.apple.finder', 'Home', '', 'Go', 'Command Shift H', 9, 117);
INSERT INTO "gui_elements" VALUES (65, 'axstatictexttextfinderdocumentsdocuments', '', 'Finder', 'com.apple.finder', 'Documents', '', 'Go', 'Command Shift O', 9, 114);
INSERT INTO "gui_elements" VALUES (66, 'axstatictexttextfinderdownloadsdownloads', '', 'Finder', 'com.apple.finder', 'Downloads', '', 'Go', 'Command Option L', 9, 116);
INSERT INTO "gui_elements" VALUES (67, 'axstatictexttextfinderapplicationsapplications', '', 'Finder', 'com.apple.finder', 'Applications', '', 'Go', 'Command Shift A', 9, 120);
INSERT INTO "gui_elements" VALUES (68, 'axbuttonclosebuttonmail', '', 'Mail', 'com.apple.mail', 'Close All Windows', '', 'File', 'Command Option W', 17, 18);
INSERT INTO "gui_elements" VALUES (69, 'axbuttonminimizebuttonmail', '', 'Mail', 'com.apple.mail', 'Minimize', '', 'Window', 'Command M', 17, 52);
INSERT INTO "gui_elements" VALUES (70, 'axbuttonfullscreenbuttonmail', '', 'Mail', 'com.apple.mail', 'Enter Full Screen', '', 'Window', 'Command Control F', 17, 74);
INSERT INTO "gui_elements" VALUES (71, 'axbuttonbuttonmailgetmail', '', 'Mail', 'com.apple.mail', 'Get All New Mail', '', 'Mailbox', 'Command Shift N', 17, 56);
INSERT INTO "gui_elements" VALUES (72, 'axbuttonbuttonmaildeletedeleteselectedmessages', '', 'Mail', 'com.apple.mail', 'Delete', 'Delete selected messages', 'File', 'Command Delete', 17, 70);
INSERT INTO "gui_elements" VALUES (73, 'axbuttonbuttonmailjunkmarkselectedmessagesasjunk', '', 'Mail', 'com.apple.mail', 'As Junk Mail', 'Mark selected messages as Junk', 'Mark', 'Command Shift U', 17, 121);
INSERT INTO "gui_elements" VALUES (74, 'axbuttonbuttonmailjunkmarkselectedmessagesasnotjunk', '', 'Mail', 'com.apple.mail', 'As Not Junk', 'Mark selected messages as Not Junk', 'Mark', 'Command Shift U', 17, 121);
INSERT INTO "gui_elements" VALUES (75, 'axbuttonbuttonmailreplyreplytosenderofselectedmessage', '', 'Mail', 'com.apple.mail', 'Reply', 'Reply to sender of selected message', 'Message', 'Command R', 17, 68);
INSERT INTO "gui_elements" VALUES (76, 'axbuttonbuttonmailreplyallreplytoallrecipientsoftheselectedmessage', '', 'Mail', 'com.apple.mail', 'Reply All', 'Reply to all recipients of the selected message', 'Message', 'Command Shift R', 17, 118);
INSERT INTO "gui_elements" VALUES (77, 'axbuttonbuttonmailforwardforwardselectedmessages', '', 'Mail', 'com.apple.mail', 'Forward', 'Forward selected messages', 'Message', 'Command Shift F', 17, 113);
INSERT INTO "gui_elements" VALUES (78, 'axbuttonbuttonmailflagred', '', 'Mail', 'com.apple.mail', 'Red', 'Flag Red', 'Flag', 'Command Shift L', 17, 11);
INSERT INTO "gui_elements" VALUES (79, 'axbuttonbuttonmailunflagred', '', 'Mail', 'com.apple.mail', 'Red', 'Unflag Red', 'Flag', 'Command Shift L', 17, 11);
INSERT INTO "gui_elements" VALUES (80, 'axbuttonbuttonmailarchive', '', 'Mail', 'com.apple.mail', 'Archive', '', 'Message', 'Command Control A', 17, 150);
INSERT INTO "gui_elements" VALUES (81, 'axbuttonbuttonmailnewmessage', '', 'Mail', 'com.apple.mail', 'New Message', '', 'File', 'Command N', 17, 15);
INSERT INTO "gui_elements" VALUES (82, 'axbuttonbuttonmailsidebar', '', 'Mail', 'com.apple.mail', 'Show/Hide Mailbox List', '', 'View', 'Command Shift M', 17, 136);
INSERT INTO "gui_elements" VALUES (83, 'axbuttonbuttonmailprint', '', 'Mail', 'com.apple.mail', 'Print', '', 'File', 'Command P', 17, 22);
INSERT INTO "gui_elements" VALUES (84, 'axbuttonbuttonmailunreadmarkselectedmessagesasunread', '', 'Mail', 'com.apple.mail', 'As Unread', 'Mark selected messages as unread', 'Mark', 'Command Shift U', 17, 121);
INSERT INTO "gui_elements" VALUES (85, 'axbuttonbuttonmailreadmarkselectedmessagesasread', '', 'Mail', 'com.apple.mail', 'As Read', 'Mark selected messages as read', 'Mark', 'Command Shift U', 17, 121);
INSERT INTO "gui_elements" VALUES (86, 'axbuttonbuttonmailaddress', '', 'Mail', 'com.apple.mail', 'Address Panel', '', 'Window', 'Command Option A', 17, 77);
INSERT INTO "gui_elements" VALUES (87, 'axbuttonbuttonmailaddsender', '', 'Mail', 'com.apple.mail', 'Add Sender to Contacts', '', 'Message', 'Command Shift Y', 17, 9);
INSERT INTO "gui_elements" VALUES (88, 'axtextfieldsearchtextfieldmailsearchaxsearchfield', '', 'Mail', 'com.apple.mail', 'Mailbox Search', '', 'Find', 'Command Option F', 17, 75);
INSERT INTO "gui_elements" VALUES (89, 'axbuttonbuttonmailhidemailboxlisthide', '', 'Mail', 'com.apple.mail', 'Hide Mailbox List', '', 'View', 'Command Shift M', 17, 136);
INSERT INTO "gui_elements" VALUES (90, 'axbuttonbuttonmailshowmailboxlistshow', '', 'Mail', 'com.apple.mail', 'Show Mailbox List', '', 'View', 'Command Shift M', 17, 136);
INSERT INTO "gui_elements" VALUES (91, 'axcheckboxcheckboxmailinbox', '', 'Mail', 'com.apple.mail', 'Inbox', '', 'Go to Favorite Mailbox', 'Command 1', 17, 78);
INSERT INTO "gui_elements" VALUES (92, 'axcheckboxcheckboxmailsent', '', 'Mail', 'com.apple.mail', 'Sent', '', 'Go to Favorite Mailbox', 'Command 2', 17, 79);
INSERT INTO "gui_elements" VALUES (93, 'axcheckboxcheckboxmailflagged', '', 'Mail', 'com.apple.mail', 'Flagged', '', 'Go to Favorite Mailbox', 'Command 3', 17, 80);
INSERT INTO "gui_elements" VALUES (97, 'axtextfieldtextfieldmailmailboxinboxinbox', '', 'Mail', 'com.apple.mail', 'Inbox', '', 'Go to Favorite Mailbox', 'Command 1', 17, 78);
INSERT INTO "gui_elements" VALUES (98, 'axtextfieldtextfieldmailmailboxsentsent', '', 'Mail', 'com.apple.mail', 'Sent Mail', '', 'Go to Favorite Mailbox', 'Command 2', 17, 79);
INSERT INTO "gui_elements" VALUES (99, 'axtextfieldtextfieldmailmailboxflaggedflagged', '', 'Mail', 'com.apple.mail', 'Flagged', '', 'Go to Favorite Mailbox', 'Command 3', 17, 80);
INSERT INTO "gui_elements" VALUES (100, 'axbuttonminimizebuttoncalendar', '', 'Calendar', 'com.apple.iCal', 'Minimize', '', 'Window', 'Command M', 31, 52);
INSERT INTO "gui_elements" VALUES (101, 'axbuttonfullscreenbuttoncalendar', '', 'Calendar', 'com.apple.iCal', 'Enter Full Screen', '', 'Window', 'Command Control F', 31, 74);
INSERT INTO "gui_elements" VALUES (102, 'axbuttonbuttoncalendaraddevent', '', 'Calendar', 'com.apple.iCal', 'New Event', '', 'File', 'Command N', 31, 15);
INSERT INTO "gui_elements" VALUES (103, 'axradiobuttonradiobuttoncalendarday', '', 'Calendar', 'com.apple.iCal', 'By Day', '', 'View', 'Command 1', 31, 78);
INSERT INTO "gui_elements" VALUES (104, 'axradiobuttonradiobuttoncalendarweek', '', 'Calendar', 'com.apple.iCal', 'By Week', '', 'View', 'Command 2', 31, 79);
INSERT INTO "gui_elements" VALUES (105, 'axradiobuttonradiobuttoncalendarmonth', '', 'Calendar', 'com.apple.iCal', 'By Month', '', 'View', 'Command 3', 31, 80);
INSERT INTO "gui_elements" VALUES (106, 'axtoolbarnotimplementedcalendar', '', 'Calendar', 'com.apple.iCal', 'By Year', '', 'View', 'Command 4', 31, 81);
INSERT INTO "gui_elements" VALUES (107, 'axtextfieldsearchtextfieldcalendarsearchfieldaxsearchfield', 'axtextfieldsearchtextfieldsearchfield_ns:32', 'Calendar', 'com.apple.iCal', 'Find', '', 'File', 'Command F', 31, 29);
INSERT INTO "gui_elements" VALUES (108, 'axbuttonbuttoncalendarpreviousyear', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 31, 246);
INSERT INTO "gui_elements" VALUES (109, 'axbuttonbuttoncalendarpreviousmonth', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 31, 246);
INSERT INTO "gui_elements" VALUES (110, 'axbuttonbuttoncalendarpreviousweek', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 31, 246);
INSERT INTO "gui_elements" VALUES (111, 'axbuttonbuttoncalendarpreviousday', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 31, 246);
INSERT INTO "gui_elements" VALUES (112, 'axbuttonbuttoncalendarnextday', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 31, 245);
INSERT INTO "gui_elements" VALUES (113, 'axbuttonbuttoncalendarnextweek', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 31, 245);
INSERT INTO "gui_elements" VALUES (114, 'axbuttonbuttoncalendarnextmonth', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 31, 245);
INSERT INTO "gui_elements" VALUES (115, 'axbuttonbuttoncalendarnextyear', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 31, 245);
INSERT INTO "gui_elements" VALUES (116, 'axbuttonbuttoncalendartoday', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command T', 31, 37);
INSERT INTO "gui_elements" VALUES (117, 'axbuttonbuttonmailsend', '', 'Mail', 'com.apple.mail', 'Send', '', 'Message', 'Command Shift D', 17, 115);
INSERT INTO "gui_elements" VALUES (118, 'axbuttonbuttonmailattach', '', 'Mail', 'com.apple.mail', 'Attach Files', '', 'File', 'Command Shift A', 17, 120);
INSERT INTO "gui_elements" VALUES (119, 'axcheckboxcheckboxmailboldboldtext', '', 'Mail', 'com.apple.mail', 'Bold', 'Bold text', 'Style', 'Command B', 17, 38);
INSERT INTO "gui_elements" VALUES (120, 'axcheckboxcheckboxmailmaketextitalic', '', 'Mail', 'com.apple.mail', 'Italic', 'Make text italic', 'Style', 'Command I', 17, 39);
INSERT INTO "gui_elements" VALUES (121, 'axcheckboxcheckboxmailunderlinemaketextunderlined', '', 'Mail', 'com.apple.mail', 'Underline', 'Make text underlined', 'Style', 'Command U', 17, 40);
INSERT INTO "gui_elements" VALUES (122, 'axbuttonbuttonmailaligntexttotheleft', '', 'Mail', 'com.apple.mail', 'Align Left', 'Align text to the left', 'Alignment', 'Command {', 17, 46);
INSERT INTO "gui_elements" VALUES (123, 'axbuttonbuttonmailcentertext', '', 'Mail', 'com.apple.mail', 'Center ', 'Center text', 'Alignment', 'Command |', 17, 47);
INSERT INTO "gui_elements" VALUES (124, 'axbuttonbuttonmailaligntexttotheright', '', 'Mail', 'com.apple.mail', 'Align Right', 'Align text to the right', 'Alignment', 'Command }', 17, 48);
INSERT INTO "gui_elements" VALUES (125, 'axstatictexttextmailtogo210@googlemailcomtogo210@googlemailcom', '', 'Mail', 'com.apple.mail', 'Align Right', '', 'Alignment', 'Command }', 17, 48);
INSERT INTO "gui_elements" VALUES (126, 'axbuttonbuttonmailreplyall', '', 'Mail', 'com.apple.mail', 'Reply All', 'Switch Reply to all(Command Shift R) or one(Command R) person', 'Message', 'Command R', 17, 68);
INSERT INTO "gui_elements" VALUES (127, 'axbuttonbuttonsafariaddbookmark', '', 'Safari', 'com.apple.Safari', 'Add Bookmark', '', 'Bookmarks', 'Command D', 36, 63);
INSERT INTO "gui_elements" VALUES (128, 'axbuttonbuttonsafariautofill', '', 'Safari', 'com.apple.Safari', 'AutoFill Form', '', 'Edit', 'Command Shift A', 36, 120);
INSERT INTO "gui_elements" VALUES (130, 'axbuttonbuttonsafarinewtabcreateanewtab', '', 'Safari', 'com.apple.Safari', 'New Tab', 'Create a new tab', 'File', 'Command T', 36, 37);
INSERT INTO "gui_elements" VALUES (131, 'axstatictexttextfinderprogrammeprogramme', '', 'Finder', 'com.apple.finder', 'In den Papierkorb legen', '', 'Gehe zu', 'Command Shift A', 9, 120);
INSERT INTO "gui_elements" VALUES (132, 'axstatictexttextfinderallemeinedateienallemeinedateien', '', 'Finder', 'com.apple.finder', 'Alle meine Dateien', '', 'Gehe zu', 'Command Shift F', 9, 113);
INSERT INTO "gui_elements" VALUES (133, 'axstatictexttextfinderschreibtischschreibtisch', '', 'Finder', 'com.apple.finder', 'Schreibtisch', '', 'Gehe zu', 'Command Shift D', 9, 115);
INSERT INTO "gui_elements" VALUES (134, 'axstatictexttextfinderbenutzerordnerbenutzerordner', '', 'Finder', 'com.apple.finder', 'Benutzerordner', '', 'Gehe zu', 'Command Shift H', 9, 117);
INSERT INTO "gui_elements" VALUES (135, 'axstatictexttextfinderdokumentedokumente', '', 'Finder', 'com.apple.finder', 'Dokumente', '', 'Gehe zu', 'Command Shift O', 9, 114);
INSERT INTO "gui_elements" VALUES (136, 'axbuttonschließen-tastefinder', '', 'Finder', 'com.apple.finder', 'Schließen', '', 'Ablage', 'Command W', 9, 17);
INSERT INTO "gui_elements" VALUES (137, 'axbuttontastezumminimierenfinder', '', 'Finder', 'com.apple.finder', 'Im Dock ablegen', '', 'Fenster', 'Command M', 9, 52);
INSERT INTO "gui_elements" VALUES (138, 'axbuttontastefinderneuerordnererstellensieeinenneuenordneramaktuellenort', '', 'Finder', 'com.apple.finder', 'Neuer Ordner', 'Erstellen Sie einen neuen Ordner am aktuellen Ort', 'Ablage', 'Command Shift N', 9, 56);
INSERT INTO "gui_elements" VALUES (139, 'axbuttontastefinderlöschenausgewähltesobjektindenpapierkorblegen', '', 'Finder', 'com.apple.finder', 'In den Papierkorb legen', 'Ausgewähltes Objekt in den Papierkorb legen', 'Ablage', 'Command Delete', 9, 70);
INSERT INTO "gui_elements" VALUES (140, 'axbuttontastefinderverbindenmiteinemserververbinden', '', 'Finder', 'com.apple.finder', 'Mit Server verbinden ', 'Mit einem Server verbinden', 'Gehe zu', 'Command K', 9, 122);
INSERT INTO "gui_elements" VALUES (141, 'axbuttontastefinderübersichtobjektemit„übersicht“oderalssofortigediashowanzeigen', '', 'Finder', 'com.apple.finder', 'Übersicht', 'Objekte mit „Übersicht“ oder als sofortige Diashow anzeigen', 'Ablage', 'Command Y', 9, 66);
INSERT INTO "gui_elements" VALUES (142, 'axbuttontastefinderinformationeninformationenüberdieausgewähltendateienundordnereinblenden', '', 'Finder', 'com.apple.finder', 'Informationen', 'Informationen über die ausgewählten Dateien und Ordner einblenden', 'Ablage', 'Command I', 9, 39);
INSERT INTO "gui_elements" VALUES (143, 'axradiobuttonoptionsschaltflächefindersymboldarstellung', '', 'Finder', 'com.apple.finder', 'Als Symbole', '', 'Darstellung', 'Command 1', 9, 78);
INSERT INTO "gui_elements" VALUES (144, 'axradiobuttonoptionsschaltflächefinderlistendarstellung', '', 'Finder', 'com.apple.finder', 'Als Liste', '', 'Darstellung', 'Command 2', 9, 79);
INSERT INTO "gui_elements" VALUES (145, 'axradiobuttonoptionsschaltflächefinderspaltendarstellung', '', 'Finder', 'com.apple.finder', 'Als Spalten', '', 'Darstellung', 'Command 3', 9, 80);
INSERT INTO "gui_elements" VALUES (146, 'axradiobuttonoptionsschaltflächefindercoverflowdarstellung', '', 'Finder', 'com.apple.finder', 'Als Cover Flow', '', 'Darstellung', 'Command 4', 9, 81);
INSERT INTO "gui_elements" VALUES (147, 'axbuttontastefinderzurück', '', 'Finder', 'com.apple.finder', 'Zurück', '', 'Gehe zu', 'Command Ö', 9, 113);
INSERT INTO "gui_elements" VALUES (148, 'axbuttontastefinderweiter', '', 'Finder', 'com.apple.finder', 'Vorwärts', '', 'Gehe zu', 'Command Ä', 9, 114);
INSERT INTO "gui_elements" VALUES (149, 'axbuttontastefinderauswerfenwechselmedienauswerfenundvonserverntrennen', '', 'Finder', 'com.apple.finder', 'Auswerfen', 'Wechselmedien auswerfen und von Servern trennen', 'Ablage', 'Command E', 9, 32);
INSERT INTO "gui_elements" VALUES (150, 'axtextfieldfeldfürsuchtextfindersuchenaxsearchfield', 'axtextfieldfeldfürsuchtextsuchen_ns:120', 'Finder', 'com.apple.finder', 'Suchen', '', 'Ablage', 'Command F', 9, 29);
INSERT INTO "gui_elements" VALUES (151, 'axbuttonschließen-tastechrome', '', 'Chrome', 'com.google.Chrome', 'Fenster schließen', '', 'Ablage', 'Command Shift W', 24, 132);
INSERT INTO "gui_elements" VALUES (152, 'axbuttontastezumminimierenchrome', '', 'Chrome', 'com.google.Chrome', 'Minimieren', '', 'Fenster', 'Command M', 24, 52);
INSERT INTO "gui_elements" VALUES (153, 'axbuttontastechromeneuertabneuertab', 'axbuttontasteneuertab_ns:20', 'Chrome', 'com.google.Chrome', 'Neuer Tab', 'Neuer Tab', 'Ablage', 'Command T', 24, 37);
INSERT INTO "gui_elements" VALUES (154, 'axbuttontastechromeschließen', 'axbuttontasteschließen_ns:10', 'Chrome', 'com.google.Chrome', 'Tab schließen', '', 'Ablage', 'Command W', 24, 17);
INSERT INTO "gui_elements" VALUES (155, 'axbuttontaste„vollbildmodus“chrome', '', 'Chrome', 'com.google.Chrome', 'Vollbildmodus ein', '', 'Anzeigen', 'Command Control F', 24, 74);
INSERT INTO "gui_elements" VALUES (156, 'axbuttontastechromezurückklicken,umzurückzugehen.gedrückthalten,umverlaufaufzurufen', 'axbuttontastezurück_ns:10', 'Chrome', 'com.google.Chrome', 'Zurück', 'Klicken, um zurückzugehen. Gedrückt halten, um Verlauf aufzurufen', 'Verlauf', 'Command [', 24, 105);
INSERT INTO "gui_elements" VALUES (157, 'axbuttontastechromevorwärtsklicken,umweiterzugehen.gedrückthalten,umverlaufaufzurufen', 'axbuttontastevorwärts_ns:32', 'Chrome', 'com.google.Chrome', 'Vorwärts', 'Klicken, um weiterzugehen. Gedrückt halten, um Verlauf aufzurufen', 'Verlauf', 'Command ]', 24, 106);
INSERT INTO "gui_elements" VALUES (158, 'axbuttontastechromeneuladendieseseiteneuladen', '', 'Chrome', 'com.google.Chrome', 'Stopp', 'Seite nicht weiter laden', 'Anzeigen', 'Command .', 24, 215);
INSERT INTO "gui_elements" VALUES (159, 'axbuttontastechromeneuladenseitenichtweiterladen', '', 'Chrome', 'com.google.Chrome', 'Diese Seite neu laden', 'Diese Seite neu laden', 'Anzeigen', 'Command R', 24, 68);
INSERT INTO "gui_elements" VALUES (160, 'axbuttontastechromestartseitestartseiteöffnen', 'axbuttontastestartseite_ns:37', 'Chrome', 'com.google.Chrome', 'Startseite', 'Startseite öffnen', 'Anzeigen', 'Command Shift H', 24, 117);
INSERT INTO "gui_elements" VALUES (161, 'axtextfieldtextfeldchromeadresse', 'axtextfieldtextfeldadresse_ns:44', 'Chrome', 'com.google.Chrome', 'Adresse öffnen', '', 'Ablage', 'Command L', 24, 65);
INSERT INTO "gui_elements" VALUES (162, 'axbuttontastechrome1password1password', '', 'Chrome', 'com.google.Chrome', '1Password', '1Password', 'Anzeigen', 'Command \', 24, 224);
INSERT INTO "gui_elements" VALUES (163, 'axbuttonschließen-tastecalendar', '', 'Calendar', 'com.apple.iCal', 'Schließen', '', 'Ablage', 'Command W', 31, 17);
INSERT INTO "gui_elements" VALUES (164, 'axbuttontastezumminimierencalendar', '', 'Calendar', 'com.apple.iCal', 'Im Dock ablegen', '', 'Fenster', 'Command M', 31, 52);
INSERT INTO "gui_elements" VALUES (165, 'axbuttontastecalendarereignishinzufügen', '', 'Calendar', 'com.apple.iCal', 'Neues Ereignis', '', 'Ablage', 'Command N', 31, 15);
INSERT INTO "gui_elements" VALUES (166, 'axradiobuttonoptionsschaltflächecalendartag', '', 'Calendar', 'com.apple.iCal', 'Tagesansicht', '', 'Darstellung', 'Command 1', 31, 78);
INSERT INTO "gui_elements" VALUES (167, 'axbuttontastecalendarvorherigertag', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (168, 'axbuttontastecalendarnächstertag', '', 'Calendar', 'com.apple.iCal', 'Nächster', '', 'Darstellung', 'Command  Right Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (169, 'axradiobuttonoptionsschaltflächecalendarwoche', '', 'Calendar', 'com.apple.iCal', 'Wochenansicht', '', 'Darstellung', 'Command 2', 31, 79);
INSERT INTO "gui_elements" VALUES (170, 'axradiobuttonoptionsschaltflächecalendarmonat', '', 'Calendar', 'com.apple.iCal', 'Monatsansicht', '', 'Darstellung', 'Command 3', 31, 80);
INSERT INTO "gui_elements" VALUES (171, 'axradiobuttonoptionsschaltflächecalendarjahr', '', 'Calendar', 'com.apple.iCal', 'Jahresansicht', '', 'Darstellung', 'Command 4', 31, 81);
INSERT INTO "gui_elements" VALUES (172, 'axtextfieldfeldfürsuchtextcalendarsuchfeldaxsearchfield', 'axtextfieldfeldfürsuchtextsuchfeld_ns:34', 'Calendar', 'com.apple.iCal', 'Suchen', '', 'Bearbeiten', 'Command F', 31, 29);
INSERT INTO "gui_elements" VALUES (173, 'axbuttontastecalendarvorherigesjahr', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (174, 'axbuttontastecalendarvorherigermonat', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (175, 'axbuttontastecalendarvorherigewoche', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (176, 'axbuttontastecalendarnächstewoche', '', 'Calendar', 'com.apple.iCal', 'Nächste', '', 'Darstellung', 'Command  Right Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (177, 'axbuttontastecalendarnächstermonat', '', 'Calendar', 'com.apple.iCal', 'Nächste', '', 'Darstellung', 'Command  Right Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (178, 'axbuttontastecalendarnächstesjahr', '', 'Calendar', 'com.apple.iCal', 'Nächste', '', 'Darstellung', 'Command  Right Arrow ', 31, NULL);
INSERT INTO "gui_elements" VALUES (179, 'axbuttontastecalendarheute', '', 'Calendar', 'com.apple.iCal', 'Heute anzeigen', '', 'Darstellung', 'Command T', 31, 37);
INSERT INTO "gui_elements" VALUES (180, 'axbuttonschließen-tastesafari', '', 'Safari', 'com.apple.Safari', 'Fenster schließen', '', 'Ablage', 'Command W', 36, 17);
INSERT INTO "gui_elements" VALUES (181, 'axbuttontastezumminimierensafari', '', 'Safari', 'com.apple.Safari', 'Im Dock ablegen', '', 'Fenster', 'Command M', 36, 52);
INSERT INTO "gui_elements" VALUES (182, 'axbuttontaste„vollbildmodus“safari', '', 'Safari', 'com.apple.Safari', 'Vollbild ein', '', 'Darstellung', 'Command Control F', 36, 74);
INSERT INTO "gui_elements" VALUES (184, 'axbuttontastesafarivorwärtsdienächsteseiteanzeigen', '', 'Safari', 'com.apple.Safari', 'Vorwärts', 'Die nächste Seite anzeigen', 'Verlauf', 'Command Shift Ä', 36, 254);
INSERT INTO "gui_elements" VALUES (185, 'axbuttontastesafarizurückdievorherigeseiteanzeigen', '', 'Safari', 'com.apple.Safari', 'Zurück', 'Die vorherige Seite anzeigen', 'Verlauf', 'Command Shift Ö', 36, 253);
INSERT INTO "gui_elements" VALUES (186, 'axbuttontastesafarileseliste', '', 'Safari', 'com.apple.Safari', 'Leseliste einblenden', 'Leseliste ein-/ausblenden', 'Darstellung', 'Command Shift L', 36, 11);
INSERT INTO "gui_elements" VALUES (187, 'axbuttontastesafaritopsites', '', 'Safari', 'com.apple.Safari', 'Top Sites einblenden', '', 'Verlauf', 'Command Option 1', 36, 82);
INSERT INTO "gui_elements" VALUES (188, 'axbuttontastesafaristartseite', '', 'Safari', 'com.apple.Safari', 'Startseite', '', 'Verlauf', 'Command Shift H', 36, 117);
INSERT INTO "gui_elements" VALUES (189, 'axbuttontastesafarineuertab', '', 'Safari', 'com.apple.Safari', 'Neuer Tab', '', 'Ablage', 'Command T', 36, 37);
INSERT INTO "gui_elements" VALUES (190, 'axbuttontastesafariverlauf', '', 'Safari', 'com.apple.Safari', 'Gesamten Verlauf anzeigen', '', 'Verlauf', 'Command Option 2', 36, 83);
INSERT INTO "gui_elements" VALUES (191, 'axbuttontastesafarilesezeichen', '', 'Safari', 'com.apple.Safari', 'Alle Lesezeichen anzeigen', 'Alle Lesezeichen ein-/ausblenden', 'Verlauf', 'Command Option B', 36, 233);
INSERT INTO "gui_elements" VALUES (192, 'axbuttontastesafarilesezeichenhinzufügen', '', 'Safari', 'com.apple.Safari', 'Lesezeichen hinzufügen', '', 'Lesezeichen', 'Command D', 36, 63);
INSERT INTO "gui_elements" VALUES (193, 'axbuttontastesafarilesezeichenleiste', '', 'Safari', 'com.apple.Safari', 'Lesezeichenleiste einblenden', 'Lesezeichenleiste ein-/ausblenden', 'Darstellung', 'Command Shift B', 36, 210);
INSERT INTO "gui_elements" VALUES (194, 'axbuttontastesafariautom.ausfüllen', '', 'Safari', 'com.apple.Safari', 'Formular automatisch ausfüllen', '', 'Bearbeiten', 'Command Shift A', 36, 120);
INSERT INTO "gui_elements" VALUES (195, 'axbuttontastesafariverkleinernverkleinern', '', 'Safari', 'com.apple.Safari', 'Verkleinern', 'Verkleinern', 'Darstellung', 'Command -', 36, 42);
INSERT INTO "gui_elements" VALUES (196, 'axbuttontastesafarivergrößernvergrößern', '', 'Safari', 'com.apple.Safari', 'Vergrößern', 'Vergrößern', 'Darstellung', 'Command +', 36, 41);
INSERT INTO "gui_elements" VALUES (197, 'axbuttontastesafarimail', '', 'Safari', 'com.apple.Safari', 'Diese Seite per E-Mail senden', '', 'Senden', 'Command I', 36, 39);
INSERT INTO "gui_elements" VALUES (198, 'axbuttontastesafaridrucken', '', 'Safari', 'com.apple.Safari', 'Drucken', '', 'Ablage', 'Command P', 36, 22);
INSERT INTO "gui_elements" VALUES (199, 'axbuttontastesafariwebinformationen', '', 'Safari', 'com.apple.Safari', 'Webinformationen einblenden', '', 'Entwickler', 'Command Option I', 36, 61);
INSERT INTO "gui_elements" VALUES (200, 'axtextfieldtextfeldsafariadresseundsuchen', 'axtextfieldtextfeldadresseundsuchenweb_browser_address_and_search_field', 'Safari', 'com.apple.Safari', 'Adresse öffnen', 'Suchbegriff, Webseitenadresse, Titel oder Lesezeichen eingeben', 'Ablage', 'Command L', 36, 65);
INSERT INTO "gui_elements" VALUES (201, 'axbuttontastesafarireaderein-/ausblendenreader', 'axbuttontastereaderreaderein-/ausblenden_ns:173', 'Safari', 'com.apple.Safari', 'Reader einblenden', 'Reader ein-/ausblenden', 'Darstellung', 'Command Shift R', 36, 118);
INSERT INTO "gui_elements" VALUES (202, 'axbuttontastesafarireaderein-/ausblendenreadereinblendenreader', 'axbuttontastereaderreaderein-/ausblenden_ns:173', 'Safari', 'com.apple.Safari', 'Reader einblenden', 'Reader einblenden', 'Darstellung', 'Command Shift R', 36, 118);
INSERT INTO "gui_elements" VALUES (203, 'axbuttontastesafarireaderein-/ausblendenreaderausblendenreader', 'axbuttontastereaderreaderein-/ausblenden_ns:173', 'Safari', 'com.apple.Safari', 'Reader ausblenden', 'Reader ausblenden', 'Darstellung', 'Command Shift R', 36, 118);
INSERT INTO "gui_elements" VALUES (204, 'axbuttontastesafari1password1password', '', 'Safari', 'com.apple.Safari', '1Password', '1Password', 'Darstellung', 'Command \', 36, 224);
INSERT INTO "gui_elements" VALUES (205, 'axbuttontastesafaridownloads', '', 'Safari', 'com.apple.Safari', 'Downloads anzeigen', '', 'Darstellung', 'Command Option L', 36, 116);
INSERT INTO "gui_elements" VALUES (206, 'axbuttontastesafarineuladenaktuelleseiteneuladen', '', 'Safari', 'com.apple.Safari', 'Seite neu laden', 'Aktuelle Seite neu laden', 'Darstellung', 'Command R', 36, 68);
INSERT INTO "gui_elements" VALUES (207, 'axbuttontastesafaristoppladendieserseitebeenden', '', 'Safari', 'com.apple.Safari', 'Stopp', 'Laden dieser Seite beenden', 'Darstellung', 'Command .', 36, 215);
INSERT INTO "gui_elements" VALUES (208, 'axcheckboxmarkierungsfeldsafarileselisteeinblendenleselisteeinblenden', '', 'Safari', 'com.apple.Safari', 'Leseliste einblenden', 'Leseliste einblenden', 'Darstellung', 'Command Shift L', 36, 11);
INSERT INTO "gui_elements" VALUES (209, 'axcheckboxmarkierungsfeldsafarileselisteausblendenleselisteausblenden', '', 'Safari', 'com.apple.Safari', 'Leseliste ausblenden', 'Leseliste ausblenden', 'Darstellung', 'Command Shift L', 36, 11);
INSERT INTO "gui_elements" VALUES (210, 'axcheckboxmarkierungsfeldsafarilesezeichenanzeigenallelesezeicheneinblenden', 'axcheckboxmarkierungsfeldlesezeichenanzeigen_ns:24', 'Safari', 'com.apple.Safari', 'Alle Lesezeichen einblenden', 'Alle Lesezeichen einblenden', 'Darstellung', 'Command Shift B', 36, 210);
INSERT INTO "gui_elements" VALUES (211, 'axbuttontastesafaritopsiteseinblendentopsiteseinblenden', '', 'Safari', 'com.apple.Safari', 'Top Sites einblenden', 'Top Sites einblenden', 'Verlauf', 'Command Option 1', 36, 82);
INSERT INTO "gui_elements" VALUES (212, 'axbuttontastesafariklickensie,umdiesentabzuschließen.wahltaste-klickenschließtalletabsaußerdiesem.tabschließen', '', 'Safari', 'com.apple.Safari', 'Tab schließen', 'Klicken Sie, um diesen Tab zu schließen. Wahltaste-Klicken schließt alle Tabs außer diesem.', 'Ablage', 'Command W', 36, 17);
INSERT INTO "gui_elements" VALUES (213, 'axbuttontastesafarineuertabneuentaberstellen', '', 'Safari', 'com.apple.Safari', 'Neuer Tab', 'Neuen Tab erstellen', 'Ablage', 'Command T', 36, 37);
INSERT INTO "gui_elements" VALUES (214, 'axbuttontastesafarialletabseinblendenalletabseinblenden', '', 'Safari', 'com.apple.Safari', 'Alle Tabs einblenden', 'Alle Tabs einblenden', 'Darstellung', 'Command Shift \', 36, 252);
INSERT INTO "gui_elements" VALUES (215, 'axbuttontastesafariweitersuchen(rückwärts)', '', 'Safari', 'com.apple.Safari', 'Weitersuchen (rückwärts)', '', 'Suchen', 'Command Shift G', 36, 31);
INSERT INTO "gui_elements" VALUES (216, 'axbuttontastesafariweitersuchen(vorwärts)', '', 'Safari', 'com.apple.Safari', 'Weitersuchen (vorwärts)', '', 'Suchen', 'Command G', 36, 30);
INSERT INTO "gui_elements" VALUES (217, 'axtextfieldfeldfürsuchtextsafariaxsearchfield', 'axtextfieldfeldfürsuchtext_ns:27', 'Safari', 'com.apple.Safari', 'Suchen', '', 'Suchen', 'Command F', 36, 29);
INSERT INTO "gui_elements" VALUES (218, 'axbuttonschließen-tastemail', '', 'Mail', 'com.apple.mail', 'Schließen', '', 'Ablage', 'Command W', 17, 17);
INSERT INTO "gui_elements" VALUES (219, 'axbuttontastezumminimierenmail', '', 'Mail', 'com.apple.mail', 'Im Dock ablegen', '', 'Fenster', 'Command M', 17, 52);
INSERT INTO "gui_elements" VALUES (220, 'axbuttontaste„vollbildmodus“mail', '', 'Mail', 'com.apple.mail', 'Vollbild ein', '', 'Darstellung', 'Command Control F', 17, 74);
INSERT INTO "gui_elements" VALUES (221, 'axbuttontastemailempfangen', '', 'Mail', 'com.apple.mail', 'Alle neuen E-Mails empfangen', '', 'Postfach', 'Command Shift N', 17, 56);
INSERT INTO "gui_elements" VALUES (222, 'axbuttontastemailneuee-mail', '', 'Mail', 'com.apple.mail', 'Neue E-Mail', '', 'Ablage', 'Command N', 17, 15);
INSERT INTO "gui_elements" VALUES (223, 'axbuttontastemaillöschenausgewähltee-mailslöschen', '', 'Mail', 'com.apple.mail', 'Löschen', 'Ausgewählte E-Mails löschen', 'Ablage', 'Command Delete', 17, 70);
INSERT INTO "gui_elements" VALUES (224, 'axbuttontastemailistwerbungmarkierungalsunerwünschtewerbungfürausgewähltee-mailsaufheben', '', 'Mail', 'com.apple.mail', 'Als unerwünschte Werbung', 'Markierung als unerwünschte Werbung für ausgewählte E-Mails aufheben', 'Markieren', 'Command Shift J', 17, 176);
INSERT INTO "gui_elements" VALUES (225, 'axbuttontastemailistwerbungausgewähltee-mailsalsunerwünschtewerbungmarkieren', '', 'Mail', 'com.apple.mail', 'Als unerwünschte Werbung', 'Ausgewählte E-Mails als unerwünschte Werbung markieren', 'Markieren', 'Command Shift J', 17, 176);
INSERT INTO "gui_elements" VALUES (226, 'axbuttontastemaillöschen', '', 'Mail', 'com.apple.mail', 'Löschen', '', 'Ablage', 'Command Delete', 17, 70);
INSERT INTO "gui_elements" VALUES (227, 'axbuttontastemailistwerbung', '', 'Mail', 'com.apple.mail', 'Als unerwünschte Werbung', 'Als unerwünschte Werbung markieren', 'Ablage', 'Command Shift J', 17, 176);
INSERT INTO "gui_elements" VALUES (228, 'axbuttontastemailantwortendemabsenderderausgewähltene-mailantworten', '', 'Mail', 'com.apple.mail', 'Antworten', 'Dem Absender der ausgewählten E-Mail antworten', 'E-Mail', 'Command R', 17, 68);
INSERT INTO "gui_elements" VALUES (229, 'axbuttontastemailanalleallenempfängernderausgewähltene-mailantworten', '', 'Mail', 'com.apple.mail', 'An alle', 'Allen Empfängern der ausgewählten E-Mail antworten', 'E-Mail', 'Command Shift R', 17, 118);
INSERT INTO "gui_elements" VALUES (230, 'axbuttontastemailweiterleitenausgewähltee-mailsweiterleiten', '', 'Mail', 'com.apple.mail', 'Weiterleiten', 'Ausgewählte E-Mails weiterleiten', 'E-Mail', 'Command Shift F', 17, 113);
INSERT INTO "gui_elements" VALUES (231, 'axbuttontastemailantworten', '', 'Mail', 'com.apple.mail', 'Antworten', '', 'E-Mail', 'Command R', 17, 68);
INSERT INTO "gui_elements" VALUES (232, 'axbuttontastemailanalle', '', 'Mail', 'com.apple.mail', 'An alle', '', 'E-Mail', 'Command Shift R', 17, 118);
INSERT INTO "gui_elements" VALUES (233, 'axbuttontastemailweiterleiten', '', 'Mail', 'com.apple.mail', 'Weiterleiten', '', 'E-Mail', 'Command Shift F', 17, 113);
INSERT INTO "gui_elements" VALUES (234, 'axbuttontastemailetikett„red“', '', 'Mail', 'com.apple.mail', 'Red', 'Rot etikettieren', 'Etikett', 'Command Shift L', 17, 11);
INSERT INTO "gui_elements" VALUES (235, 'axbuttontastemailetikettvonredentfernen', '', 'Mail', 'com.apple.mail', 'Red', 'Rotes Etikett entfernen', 'Etikett', 'Command Shift L', 17, 11);
INSERT INTO "gui_elements" VALUES (236, 'axbuttontastemailarchivieren', '', 'Mail', 'com.apple.mail', 'Archivieren', '', 'E-Mail', 'Command Control A', 17, 150);
INSERT INTO "gui_elements" VALUES (237, 'axbuttontastemailseitenleiste', '', 'Mail', 'com.apple.mail', 'Postfachliste ausblenden', 'Postfachliste ein-/ausblenden', 'E-Mail', 'Command Shift M', 17, 136);
INSERT INTO "gui_elements" VALUES (238, 'axbuttontastemaildrucken', '', 'Mail', 'com.apple.mail', 'Drucken', '', 'Ablage', 'Command P', 17, 22);
INSERT INTO "gui_elements" VALUES (239, 'axbuttontastemailungelesenausgewähltee-mailsalsungelesenmarkieren', '', 'Mail', 'com.apple.mail', 'Ungelesen', 'Ausgewählte E-Mails als ungelesen markieren', 'Markieren', 'Command Shift U', 17, 121);
INSERT INTO "gui_elements" VALUES (240, 'axbuttontastemailgelesenausgewähltee-mailsalsgelesenmarkieren', '', 'Mail', 'com.apple.mail', 'Als gelesen', 'Ausgewählte E-Mails als gelesen markieren', 'Markieren', 'Command Shift U', 17, 121);
INSERT INTO "gui_elements" VALUES (241, 'axbuttontastemailadressen', '', 'Mail', 'com.apple.mail', 'Adressen', '', 'Fenster', 'Command Option A', 17, 77);
INSERT INTO "gui_elements" VALUES (242, 'axbuttontastemailkleinerdieschriftgrößederausgewähltene-mailverkleinern', '', 'Mail', 'com.apple.mail', 'Kleiner', 'Die Schriftgröße der ausgewählten E-Mail verkleinern', 'Stil', 'Command -', 17, 42);
INSERT INTO "gui_elements" VALUES (243, 'axbuttontastemailgrößerdieschriftgrößederausgewähltene-mailvergrößern', '', 'Mail', 'com.apple.mail', 'Größer', 'Die Schriftgröße der ausgewählten E-Mail vergrößern', 'Stil', 'Command +', 17, 41);
INSERT INTO "gui_elements" VALUES (244, 'axbuttontastemailabsenderhinzufügen', '', 'Mail', 'com.apple.mail', 'Absender zu Kontakten hinzufügen', '', 'E-Mail', 'Command Shift Y', 17, 9);
INSERT INTO "gui_elements" VALUES (245, 'axtextfieldfeldfürsuchtextmailsuchenaxsearchfield', '', 'Mail', 'com.apple.mail', 'Postfach durchsuchen', '', 'Suchen', 'Command Option F', 17, 75);
INSERT INTO "gui_elements" VALUES (246, 'axbuttontastemailpostfachlisteeinblendeneinblenden', '', 'Mail', 'com.apple.mail', 'Postfachliste einblenden', '', 'Suchen', 'Command Shift M', 17, 136);
INSERT INTO "gui_elements" VALUES (247, 'axbuttontastemailpostfachlisteausblendenausblenden', '', 'Mail', 'com.apple.mail', 'Postfachliste ausblenden', '', 'Darstellung', 'Command Shift M', 17, 136);
INSERT INTO "gui_elements" VALUES (248, 'axcheckboxmarkierungsfeldmaileingang', '', 'Mail', 'com.apple.mail', 'Eingang', '', 'Favoriten-Postfach öffnen', 'Command 1', 17, 78);
INSERT INTO "gui_elements" VALUES (249, 'axcheckboxmarkierungsfeldmailgesendet', '', 'Mail', 'com.apple.mail', 'Gesendet', '', 'Favoriten-Postfach öffnen', 'Command 2', 17, 79);
INSERT INTO "gui_elements" VALUES (250, 'axcheckboxmarkierungsfeldmailmarkiert', '', 'Mail', 'com.apple.mail', 'Markiert', '', 'Favoriten-Postfach öffnen', 'Command 3', 17, 80);
INSERT INTO "gui_elements" VALUES (251, 'axtextfieldtextfeldmailpostfacheingangeingang', '', 'Mail', 'com.apple.mail', 'Eingang', '', 'Favoriten-Postfach öffnen', 'Command 1', NULL, 78);
INSERT INTO "gui_elements" VALUES (252, 'axtextfieldtextfeldmailpostfachmarkiertmarkiert', '', 'Mail', 'com.apple.mail', 'Markiert', '', 'Favoriten-Postfach öffnen', 'Command 3', NULL, 80);
INSERT INTO "gui_elements" VALUES (253, 'axtextfieldtextfeldmailpostfachgesendetgesendet', '', 'Mail', 'com.apple.mail', 'Gesendet', '', 'Favoriten-Postfach öffnen', 'Command 2', NULL, 79);
INSERT INTO "gui_elements" VALUES (254, 'axbuttontastemailsenden', '', 'Mail', 'com.apple.mail', 'Senden', '', 'E-Mail', 'Command Shift D', NULL, 115);
INSERT INTO "gui_elements" VALUES (255, 'axbuttontastemailanhang', '', 'Mail', 'com.apple.mail', 'Anhänge hinzufügen', '', 'Ablage', 'Command Shift A', NULL, 120);
INSERT INTO "gui_elements" VALUES (256, 'axcheckboxmarkierungsfeldmailfettfettertext', '', 'Mail', 'com.apple.mail', 'Fett', 'Fetter Text', 'Stil', 'Command B', NULL, 38);
INSERT INTO "gui_elements" VALUES (257, 'axcheckboxmarkierungsfeldmailtextalskursivschrift', '', 'Mail', 'com.apple.mail', 'Kursiv', 'Text als Kursivschrift', 'Stil', 'Command I', NULL, 39);
INSERT INTO "gui_elements" VALUES (258, 'axcheckboxmarkierungsfeldmailunterstrichentextunterstrichen', '', 'Mail', 'com.apple.mail', 'Unterstrichen', 'Text unterstrichen', 'Stil', 'Command U', NULL, 40);
INSERT INTO "gui_elements" VALUES (259, 'axbuttontastemailtextlinksbündigausrichten', '', 'Mail', 'com.apple.mail', 'Linksbündig', 'Text linksbündig ausrichten', 'Ausrichtung', 'Command {', NULL, 46);
INSERT INTO "gui_elements" VALUES (260, 'axbuttontastemailtextzentrieren', '', 'Mail', 'com.apple.mail', 'Zentriert', 'Text zentrieren', 'Ausrichtung', 'Command |', NULL, 47);
INSERT INTO "gui_elements" VALUES (261, 'axbuttontastemailtextrechtsbündigausrichten', '', 'Mail', 'com.apple.mail', 'Rechtsbündig', 'Text rechtsbündig ausrichten', 'Ausrichtung', 'Command }', NULL, 48);
