INSERT INTO "gui_elements" VALUES (1, 'axbuttonclosebuttonsafari', '', 'Safari', 'com.apple.Safari', 'Close Window', '', 'File', 'Command Shift W', 30, 229);
INSERT INTO "gui_elements" VALUES (2, 'axbuttonminimizebuttonsafari', '', 'Safari', 'com.apple.Safari', 'Minimize', '', 'Window', 'Command M', 30, 52);
INSERT INTO "gui_elements" VALUES (3, 'axbuttonfullscreenbuttonsafari', '', 'Safari', 'com.apple.Safari', 'Enter Full Screen', '', 'View', 'Command Control F', 30, 74);
INSERT INTO "gui_elements" VALUES (4, 'axtextfieldtextfieldsafariaddressandsearch', 'WEB_BROWSER_ADDRESS_AND_SEARCH_FIELD', 'Safari', 'com.apple.Safari', 'Open Location…', 'Type a word or phrase to search for, or a webpage address, title, or bookmark', 'File', 'Command L', 30, 65);
INSERT INTO "gui_elements" VALUES (5, 'axbuttonbuttonsafarireloadreloadthecurrentpage', '', 'Safari', 'com.apple.Safari', 'Reload Page', 'Reload the current page', 'View', 'Command R', 30, 68);
INSERT INTO "gui_elements" VALUES (6, 'axbuttonbuttonsafaristopstoploadingthispage', '', 'Safari', 'com.apple.Safari', 'Stop', 'Stop loading this page', 'View', 'Command .', 30, 212);
INSERT INTO "gui_elements" VALUES (7, 'axbuttonbuttonsafaritogglereaderreader', '_NS:173', 'Safari', 'com.apple.Safari', 'Show Reader', 'Show/Hide Reader', 'View', 'Command Shift R', 30, 118);
INSERT INTO "gui_elements" VALUES (8, 'axbuttonbuttonsafarireadinglist', '', 'Safari', 'com.apple.Safari', 'Show Reading List', 'Show/Hide Reading List', 'View', 'Command Shift L', 30, 11);
INSERT INTO "gui_elements" VALUES (9, 'axbuttonbuttonsafariaddpage', '', 'Safari', 'com.apple.Safari', 'Add to Reading List', '', 'Bookmarks', 'Command Shift D', 30, 115);
INSERT INTO "gui_elements" VALUES (10, 'axbuttonbuttonsafaritopsites', '', 'Safari', 'com.apple.Safari', 'Show Top Sites', '', 'History', 'Command Option 1', 30, 82);
INSERT INTO "gui_elements" VALUES (11, 'axbuttonbuttonsafarihome', '', 'Safari', 'com.apple.Safari', 'Home', '', 'History', 'Command Shift H', 30, 117);
INSERT INTO "gui_elements" VALUES (12, 'axbuttonbuttonsafarinewtab', '', 'Safari', 'com.apple.Safari', 'New Tab', '', 'File', 'Command T', 30, 37);
INSERT INTO "gui_elements" VALUES (13, 'axbuttonbuttonsafarihistory', '', 'Safari', 'com.apple.Safari', 'Show All History', '', 'History', 'Command Option 2', 30, 83);
INSERT INTO "gui_elements" VALUES (14, 'axbuttonbuttonsafaribookmarks', '', 'Safari', 'com.apple.Safari', 'Show All Bookmarks', '', 'Bookmarks', 'Command Option B', 30, 228);
INSERT INTO "gui_elements" VALUES (15, 'axbuttonbuttonsafaribookmarksbar', '', 'Safari', 'com.apple.Safari', 'Hide Bookmarks Bar', 'Show/Hide Bookmarks Bar', 'View', 'Command Shift B', 30, 207);
INSERT INTO "gui_elements" VALUES (16, 'axbuttonbuttonsafarizoomoutzoomout', '', 'Safari', 'com.apple.Safari', 'Zoom Out', 'Zoom out', 'View', 'Command -', 30, 42);
INSERT INTO "gui_elements" VALUES (17, 'axbuttonbuttonsafarizoominzoomin', '', 'Safari', 'com.apple.Safari', 'Zoom In', 'Zoom in', 'View', 'Command +', 30, 41);
INSERT INTO "gui_elements" VALUES (18, 'axbuttonbuttonsafarimail', '', 'Safari', 'com.apple.Safari', 'Email Link to this Page', '', 'Share', 'Command Shift I', 30, 133);
INSERT INTO "gui_elements" VALUES (19, 'axbuttonbuttonsafariprint', '', 'Safari', 'com.apple.Safari', 'Print…', '', 'File', 'Command P', 30, 22);
INSERT INTO "gui_elements" VALUES (20, 'axbuttonbuttonsafariwebinspector', '', 'Safari', 'com.apple.Safari', 'Show Web Inspector', 'Show/Hide Web Inspector', 'Develop', 'Command Option I', 30, 61);
INSERT INTO "gui_elements" VALUES (21, 'axbuttonbuttonsafaridownloads', '', 'Safari', 'com.apple.Safari', 'Show Downloads', '', 'View', 'Command Option L', 30, 116);
INSERT INTO "gui_elements" VALUES (22, 'axbuttonbuttonsafari1password1password', '', 'Safari', 'com.apple.Safari', '1Password', '1Password', 'View', 'Command \', 30, 221);
INSERT INTO "gui_elements" VALUES (23, 'axbuttonbuttonsafaribackshowthepreviouspage', '', 'Safari', 'com.apple.Safari', 'Back', 'Show the previous page', 'History', 'Command [', 30, 105);
INSERT INTO "gui_elements" VALUES (24, 'axbuttonbuttonsafariforwardshowthenextpage', '', 'Safari', 'com.apple.Safari', 'Forward', 'Show the next page', 'History', 'Command ]', 30, 106);
INSERT INTO "gui_elements" VALUES (25, 'axcheckboxcheckboxsafarishowreadinglistshowreadinglist', '', 'Safari', 'com.apple.Safari', 'Show Reading List', 'Show Reading List', 'View', 'Command Shift L', 30, 11);
INSERT INTO "gui_elements" VALUES (26, 'axcheckboxcheckboxsafarihidereadinglisthidereadinglist', '', 'Safari', 'com.apple.Safari', 'Hide Reading List', 'Hide Reading List', 'View', 'Command Shift L', 30, 11);
INSERT INTO "gui_elements" VALUES (27, 'axcheckboxcheckboxsafarishowbookmarksshowallbookmarks', '_NS:25', 'Safari', 'com.apple.Safari', 'Show All Bookmarks', 'Show all bookmarks', 'Bookmarks', 'Command Option B', 30, 228);
INSERT INTO "gui_elements" VALUES (28, 'axcheckboxcheckboxsafarihidebookmarkshideallbookmarks', '_NS:25', 'Safari', 'com.apple.Safari', 'Hide All Bookmarks', 'Hide all bookmarks', 'Bookmarks', 'Command Option B', 30, 228);
INSERT INTO "gui_elements" VALUES (29, 'axbuttonbuttonsafarishowtopsitesshowtopsites', '', 'Safari', 'com.apple.Safari', 'Show Top Sites', 'Show Top Sites', 'History', 'Command Option 1', 30, 82);
INSERT INTO "gui_elements" VALUES (31, 'axbuttonbuttonsafarishowalltabsshowalltabs', '', 'Safari', 'com.apple.Safari', 'Show All Tabs', 'Show all tabs', 'View', 'Command Shift \', 30, 243);
INSERT INTO "gui_elements" VALUES (32, 'axbuttonclosebuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Close Window', '', 'File', 'Command Shift W', 21, 229);
INSERT INTO "gui_elements" VALUES (33, 'axbuttonminimizebuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Minimize', '', 'Window', 'Command M', 21, 52);
INSERT INTO "gui_elements" VALUES (34, 'axbuttonfullscreenbuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Enter Full Screen', '', 'Window', 'Command Control F', 21, 74);
INSERT INTO "gui_elements" VALUES (35, 'axbuttonbuttonchromenewtabnewtab', '_NS:20', 'Chrome', 'com.google.Chrome', 'New Tab', 'New tab', 'File', 'Command T', 21, 37);
INSERT INTO "gui_elements" VALUES (36, 'axbuttonbuttonchromeclose', '_NS:10', 'Chrome', 'com.google.Chrome', 'Close Tab', '', 'File', 'Command W', 21, 17);
INSERT INTO "gui_elements" VALUES (37, 'axbuttonbuttonchromebackclicktogoback,holdtoseehistory', '_NS:10', 'Chrome', 'com.google.Chrome', 'Back', 'Click to go back, hold to see history', 'History', 'Command [', 21, 105);
INSERT INTO "gui_elements" VALUES (38, 'axbuttonbuttonchromeforwardclicktogoforward,holdtoseehistory', '_NS:32', 'Chrome', 'com.google.Chrome', 'Forward', 'Click to go forward, hold to see history', 'History', 'Command ]', 21, 106);
INSERT INTO "gui_elements" VALUES (39, 'axbuttonbuttonchromehomeopenthehomepage', '_NS:37', 'Chrome', 'com.google.Chrome', 'Home', 'Open the home page', 'History', 'Command Shift H', 21, 117);
INSERT INTO "gui_elements" VALUES (40, 'axbuttonbuttonchromereloadreloadthispage', '_NS:63', 'Chrome', 'com.google.Chrome', 'Reload Page', 'Reload this page', 'View', 'Command R', 21, 68);
INSERT INTO "gui_elements" VALUES (41, 'axbuttonbuttonchromereloadstoploadingthispage', '_NS:63', 'Chrome', 'com.google.Chrome', 'Stop', 'Stop loading this page', 'View', 'Command .', 21, 212);
INSERT INTO "gui_elements" VALUES (42, 'axtextfieldtextfieldchromeaddress', '_NS:44', 'Chrome', 'com.google.Chrome', 'Open Location…', '', 'File', 'Command L', 21, 65);
INSERT INTO "gui_elements" VALUES (43, 'axbuttonbuttonchrome1password1password', '', 'Chrome', 'com.google.Chrome', '1Password', '1Password', 'View', 'Command \', 21, 221);
INSERT INTO "gui_elements" VALUES (44, 'axbuttonclosebuttonfinder', '', 'Finder', 'com.apple.finder', 'Close Window', '', 'File', 'Command W', 7, 17);
INSERT INTO "gui_elements" VALUES (45, 'axbuttonminimizebuttonfinder', '', 'Finder', 'com.apple.finder', 'Minimize', '', 'Window', 'Command M', 7, 52);
INSERT INTO "gui_elements" VALUES (46, 'axbuttonbuttonfindernewfoldercreateanewfolderinthecurrentlocation', '', 'Finder', 'com.apple.finder', 'New Folder', 'Create a new folder in the current location', 'File', 'Command Shift N', 7, 56);
INSERT INTO "gui_elements" VALUES (47, 'axbuttonbuttonfinderdeletemovetheselecteditemtothetrash', '', 'Finder', 'com.apple.finder', 'Move to Trash', 'Move the selected item to the Trash', 'File', 'Command Delete', 7, 70);
INSERT INTO "gui_elements" VALUES (48, 'axbuttonbuttonfinderconnectconnecttoaserver', '', 'Finder', 'com.apple.finder', 'Connect to Server', 'Connect to a server', 'Go', 'Command K', 7, 122);
INSERT INTO "gui_elements" VALUES (49, 'axbuttonbuttonfinderquicklookshowitemswithquicklookorasaninstantslideshow', '', 'Finder', 'com.apple.finder', 'Quick Look', 'Show items with Quick Look or as an instant slideshow', 'File', 'Command Y', 7, 66);
INSERT INTO "gui_elements" VALUES (50, 'axbuttonbuttonfindergetinfoseeinformationabouttheselectedfilesandfolders', '', 'Finder', 'com.apple.finder', 'Get Info', 'See information about the selected files and folders', 'File', 'Command I', 7, 39);
INSERT INTO "gui_elements" VALUES (51, 'axradiobuttonradiobuttonfindericonview', '', 'Finder', 'com.apple.finder', 'as Icons', '', 'View', 'Command 1', 7, 78);
INSERT INTO "gui_elements" VALUES (52, 'axradiobuttonradiobuttonfinderlistview', '', 'Finder', 'com.apple.finder', 'as List', '', 'View', 'Command 2', 7, 79);
INSERT INTO "gui_elements" VALUES (53, 'axradiobuttonradiobuttonfindercolumnview', '', 'Finder', 'com.apple.finder', 'as Columns', '', 'View', 'Command 3', 7, 80);
INSERT INTO "gui_elements" VALUES (54, 'axradiobuttonradiobuttonfindercoverflowview', '', 'Finder', 'com.apple.finder', 'as Cover Flow', '', 'View', 'Command 4', 7, 81);
INSERT INTO "gui_elements" VALUES (55, 'axbuttonbuttonfinderback', '', 'Finder', 'com.apple.finder', 'Back', '', 'Go', 'Command [', 7, 105);
INSERT INTO "gui_elements" VALUES (56, 'axbuttonbuttonfinderforward', '', 'Finder', 'com.apple.finder', 'Forward', '', 'Go', 'Command ]', 7, 106);
INSERT INTO "gui_elements" VALUES (57, 'axbuttonbuttonfinderejectejectdisksandunmountservers', '', 'Finder', 'com.apple.finder', 'Eject', 'Eject disks and unmount servers', 'File', 'Command E', 7, 32);
INSERT INTO "gui_elements" VALUES (58, 'axtextfieldsearchtextfieldfindersearchaxsearchfield', '_NS:125', 'Finder', 'com.apple.finder', 'Find', '', 'File', 'Command F', 7, 29);
INSERT INTO "gui_elements" VALUES (59, 'axbuttonbuttonsafarifindprevious', '', 'Safari', 'com.apple.Safari', 'Find Previous', '', 'File', 'Command Shift G', 30, 31);
INSERT INTO "gui_elements" VALUES (60, 'axbuttonbuttonsafarifindnext', '', 'Safari', 'com.apple.Safari', 'Find Next', '', 'Find', 'Command G', 30, 30);
INSERT INTO "gui_elements" VALUES (61, 'axstatictexttextfinderallmyfilesallmyfiles', '', 'Finder', 'com.apple.finder', 'All My Files', '', 'Go', 'Command Shift F', 7, 113);
INSERT INTO "gui_elements" VALUES (62, 'axstatictexttextfinderairdropairdrop', '', 'Finder', 'com.apple.finder', 'AirDrop', '', 'Go', 'Command Shift R', 7, 118);
INSERT INTO "gui_elements" VALUES (63, 'axstatictexttextfinderdesktopdesktop', '', 'Finder', 'com.apple.finder', 'Desktop', '', 'Go', 'Command Shift D', 7, 115);
INSERT INTO "gui_elements" VALUES (64, 'axstatictexttextfinderhomehome', '', 'Finder', 'com.apple.finder', 'Home', '', 'Go', 'Command Shift H', 7, 117);
INSERT INTO "gui_elements" VALUES (65, 'axstatictexttextfinderdocumentsdocuments', '', 'Finder', 'com.apple.finder', 'Documents', '', 'Go', 'Command Shift O', 7, 114);
INSERT INTO "gui_elements" VALUES (66, 'axstatictexttextfinderdownloadsdownloads', '', 'Finder', 'com.apple.finder', 'Downloads', '', 'Go', 'Command Option L', 7, 116);
INSERT INTO "gui_elements" VALUES (67, 'axstatictexttextfinderapplicationsapplications', '', 'Finder', 'com.apple.finder', 'Applications', '', 'Go', 'Command Shift A', 7, 120);
INSERT INTO "gui_elements" VALUES (68, 'axbuttonclosebuttonmail', '', 'Mail', 'com.apple.mail', 'Close All Windows', '', 'File', 'Command Option W', 25, 18);
INSERT INTO "gui_elements" VALUES (69, 'axbuttonminimizebuttonmail', '', 'Mail', 'com.apple.mail', 'Minimize', '', 'Window', 'Command M', 25, 52);
INSERT INTO "gui_elements" VALUES (70, 'axbuttonfullscreenbuttonmail', '', 'Mail', 'com.apple.mail', 'Enter Full Screen', '', 'Window', 'Command Control F', 25, 74);
INSERT INTO "gui_elements" VALUES (71, 'axbuttonbuttonmailgetmail', '', 'Mail', 'com.apple.mail', 'Get All New Mail', '', 'Mailbox', 'Command Shift N', 25, 56);
INSERT INTO "gui_elements" VALUES (72, 'axbuttonbuttonmaildeletedeleteselectedmessages', '', 'Mail', 'com.apple.mail', 'Delete', 'Delete selected messages', 'File', 'Command Delete', 25, 70);
INSERT INTO "gui_elements" VALUES (73, 'axbuttonbuttonmailjunkmarkselectedmessagesasjunk', '', 'Mail', 'com.apple.mail', 'As Junk Mail', 'Mark selected messages as Junk', 'Mark', 'Command Shift U', 25, 121);
INSERT INTO "gui_elements" VALUES (74, 'axbuttonbuttonmailjunkmarkselectedmessagesasnotjunk', '', 'Mail', 'com.apple.mail', 'As Not Junk', 'Mark selected messages as Not Junk', 'Mark', 'Command Shift U', 25, 121);
INSERT INTO "gui_elements" VALUES (75, 'axbuttonbuttonmailreplyreplytosenderofselectedmessage', '', 'Mail', 'com.apple.mail', 'Reply', 'Reply to sender of selected message', 'Message', 'Command R', 25, 68);
INSERT INTO "gui_elements" VALUES (76, 'axbuttonbuttonmailreplyallreplytoallrecipientsoftheselectedmessage', '', 'Mail', 'com.apple.mail', 'Reply All', 'Reply to all recipients of the selected message', 'Message', 'Command Shift R', 25, 118);
INSERT INTO "gui_elements" VALUES (77, 'axbuttonbuttonmailforwardforwardselectedmessages', '', 'Mail', 'com.apple.mail', 'Forward', 'Forward selected messages', 'Message', 'Command Shift F', 25, 113);
INSERT INTO "gui_elements" VALUES (78, 'axbuttonbuttonmailflagred', '', 'Mail', 'com.apple.mail', 'Red', 'Flag Red', 'Flag', 'Command Shift L', 25, 11);
INSERT INTO "gui_elements" VALUES (79, 'axbuttonbuttonmailunflagred', '', 'Mail', 'com.apple.mail', 'Red', 'Unflag Red', 'Flag', 'Command Shift L', 25, 11);
INSERT INTO "gui_elements" VALUES (80, 'axbuttonbuttonmailarchive', '', 'Mail', 'com.apple.mail', 'Archive', '', 'Message', 'Command Control A', 25, 232);
INSERT INTO "gui_elements" VALUES (81, 'axbuttonbuttonmailnewmessage', '', 'Mail', 'com.apple.mail', 'New Message', '', 'File', 'Command N', 25, 15);
INSERT INTO "gui_elements" VALUES (82, 'axbuttonbuttonmailsidebar', '', 'Mail', 'com.apple.mail', 'Show/Hide Mailbox List', '', 'View', 'Command Shift M', 25, 223);
INSERT INTO "gui_elements" VALUES (83, 'axbuttonbuttonmailprint', '', 'Mail', 'com.apple.mail', 'Print…', '', 'File', 'Command P', 25, 22);
INSERT INTO "gui_elements" VALUES (84, 'axbuttonbuttonmailunreadmarkselectedmessagesasunread', '', 'Mail', 'com.apple.mail', 'As Unread', 'Mark selected messages as unread', 'Mark', 'Command Shift U', 25, 121);
INSERT INTO "gui_elements" VALUES (85, 'axbuttonbuttonmailreadmarkselectedmessagesasread', '', 'Mail', 'com.apple.mail', 'As Read', 'Mark selected messages as read', 'Mark', 'Command Shift U', 25, 121);
INSERT INTO "gui_elements" VALUES (86, 'axbuttonbuttonmailaddress', '', 'Mail', 'com.apple.mail', 'Address Panel', '', 'Window', 'Command Option A', 25, 77);
INSERT INTO "gui_elements" VALUES (87, 'axbuttonbuttonmailaddsender', '', 'Mail', 'com.apple.mail', 'Add Sender to Contacts', '', 'Message', 'Command Shift Y', 25, 9);
INSERT INTO "gui_elements" VALUES (88, 'axtextfieldsearchtextfieldmailsearchaxsearchfield', '', 'Mail', 'com.apple.mail', 'Mailbox Search', '', 'Find', 'Command Option F', 25, 75);
INSERT INTO "gui_elements" VALUES (89, 'axbuttonbuttonmailhidemailboxlisthide', '', 'Mail', 'com.apple.mail', 'Hide Mailbox List', '', 'View', 'Command Shift M', 25, 223);
INSERT INTO "gui_elements" VALUES (90, 'axbuttonbuttonmailshowmailboxlistshow', '', 'Mail', 'com.apple.mail', 'Show Mailbox List', '', 'View', 'Command Shift M', 25, 223);
INSERT INTO "gui_elements" VALUES (91, 'axcheckboxcheckboxmailinbox', '', 'Mail', 'com.apple.mail', 'Inbox', '', 'Go to Favorite Mailbox', 'Command 1', 25, 78);
INSERT INTO "gui_elements" VALUES (92, 'axcheckboxcheckboxmailsent', '', 'Mail', 'com.apple.mail', 'Sent', '', 'Go to Favorite Mailbox', 'Command 2', 25, 79);
INSERT INTO "gui_elements" VALUES (93, 'axcheckboxcheckboxmailflagged', '', 'Mail', 'com.apple.mail', 'Flagged', '', 'Go to Favorite Mailbox', 'Command 3', 25, 80);
INSERT INTO "gui_elements" VALUES (97, 'axtextfieldtextfieldmailmailboxinboxinbox', '', 'Mail', 'com.apple.mail', 'Inbox', '', 'Go to Favorite Mailbox', 'Command 1', 25, 78);
INSERT INTO "gui_elements" VALUES (98, 'axtextfieldtextfieldmailmailboxsentsent', '', 'Mail', 'com.apple.mail', 'Sent Mail', '', 'Go to Favorite Mailbox', 'Command 2', 25, 79);
INSERT INTO "gui_elements" VALUES (99, 'axtextfieldtextfieldmailmailboxflaggedflagged', '', 'Mail', 'com.apple.mail', 'Flagged', '', 'Go to Favorite Mailbox', 'Command 3', 25, 80);
INSERT INTO "gui_elements" VALUES (100, 'axbuttonminimizebuttoncalendar', '', 'Calendar', 'com.apple.iCal', 'Minimize', '', 'Window', 'Command M', NULL, 52);
INSERT INTO "gui_elements" VALUES (101, 'axbuttonfullscreenbuttoncalendar', '', 'Calendar', 'com.apple.iCal', 'Enter Full Screen', '', 'Window', 'Command Control F', NULL, 74);
INSERT INTO "gui_elements" VALUES (102, 'axbuttonbuttoncalendaraddevent', '', 'Calendar', 'com.apple.iCal', 'New Event', '', 'File', 'Command N', NULL, 15);
INSERT INTO "gui_elements" VALUES (103, 'axradiobuttonradiobuttoncalendarday', '', 'Calendar', 'com.apple.iCal', 'By Day', '', 'View', 'Command 1', NULL, 78);
INSERT INTO "gui_elements" VALUES (104, 'axradiobuttonradiobuttoncalendarweek', '', 'Calendar', 'com.apple.iCal', 'By Week', '', 'View', 'Command 2', NULL, 79);
INSERT INTO "gui_elements" VALUES (105, 'axradiobuttonradiobuttoncalendarmonth', '', 'Calendar', 'com.apple.iCal', 'By Month', '', 'View', 'Command 3', NULL, 80);
INSERT INTO "gui_elements" VALUES (106, 'axtoolbarnotimplementedcalendar', '', 'Calendar', 'com.apple.iCal', 'By Year', '', 'View', 'Command 4', NULL, 81);
INSERT INTO "gui_elements" VALUES (107, 'axtextfieldsearchtextfieldcalendarsearchfieldaxsearchfield', '_NS:32', 'Calendar', 'com.apple.iCal', 'Find', '', 'File', 'Command F', NULL, 29);
INSERT INTO "gui_elements" VALUES (108, 'axbuttonbuttoncalendarpreviousyear', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (109, 'axbuttonbuttoncalendarpreviousmonth', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (110, 'axbuttonbuttoncalendarpreviousweek', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (111, 'axbuttonbuttoncalendarpreviousday', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (112, 'axbuttonbuttoncalendarnextday', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (113, 'axbuttonbuttoncalendarnextweek', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (114, 'axbuttonbuttoncalendarnextmonth', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (115, 'axbuttonbuttoncalendarnextyear', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', NULL, NULL);
INSERT INTO "gui_elements" VALUES (116, 'axbuttonbuttoncalendartoday', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command T', NULL, 37);
