INSERT INTO "gui_elements" VALUES (1, 'axbuttonclosebuttonsafari', '', 'Safari', 'com.apple.Safari', 'Close Window', '', 'File', 'Command Shift W', 23, 131);
INSERT INTO "gui_elements" VALUES (2, 'axbuttonminimizebuttonsafari', '', 'Safari', 'com.apple.Safari', 'Minimize', '', 'Window', 'Command M', 23, 52);
INSERT INTO "gui_elements" VALUES (3, 'axbuttonfullscreenbuttonsafari', '', 'Safari', 'com.apple.Safari', 'Enter Full Screen', '', 'View', 'Command Control F', 23, 82);
INSERT INTO "gui_elements" VALUES (4, 'axtextfieldtextfieldsafariaddressandsearch', 'axtextfieldtextfieldaddressandsearchweb_browser_address_and_search_field', 'Safari', 'com.apple.Safari', 'Open Location…', 'Type a word or phrase to search for, or a webpage address, title, or bookmark', 'File', 'Command L', 23, 74);
INSERT INTO "gui_elements" VALUES (5, 'axbuttonbuttonsafarireloadreloadthecurrentpage', '', 'Safari', 'com.apple.Safari', 'Reload Page', 'Reload the current page', 'View', 'Command R', 23, 56);
INSERT INTO "gui_elements" VALUES (6, 'axbuttonbuttonsafaristopstoploadingthispage', '', 'Safari', 'com.apple.Safari', 'Stop', 'Stop loading this page', 'View', 'Command .', 23, 141);
INSERT INTO "gui_elements" VALUES (7, 'axbuttonbuttonsafaritogglereaderreader', 'axbuttonbuttonreadertogglereader_ns:173', 'Safari', 'com.apple.Safari', 'Show Reader', 'Show/Hide Reader', 'View', 'Command Shift R', 23, 125);
INSERT INTO "gui_elements" VALUES (8, 'axbuttonbuttonsafarireadinglist', '', 'Safari', 'com.apple.Safari', 'Show Reading List', 'Show/Hide Reading List', 'View', 'Command Shift L', 23, 11);
INSERT INTO "gui_elements" VALUES (9, 'axbuttonbuttonsafariaddpage', '', 'Safari', 'com.apple.Safari', 'Add to Reading List', '', 'Bookmarks', 'Command Shift D', 23, 122);
INSERT INTO "gui_elements" VALUES (10, 'axbuttonbuttonsafaritopsites', '', 'Safari', 'com.apple.Safari', 'Show Top Sites', '', 'History', 'Command Option 1', 23, 90);
INSERT INTO "gui_elements" VALUES (11, 'axbuttonbuttonsafarihome', '', 'Safari', 'com.apple.Safari', 'Home', '', 'History', 'Command Shift H', 23, 124);
INSERT INTO "gui_elements" VALUES (12, 'axbuttonbuttonsafarinewtab', '', 'Safari', 'com.apple.Safari', 'New Tab', '', 'File', 'Command T', 23, 37);
INSERT INTO "gui_elements" VALUES (13, 'axbuttonbuttonsafarihistory', '', 'Safari', 'com.apple.Safari', 'Show All History', '', 'History', 'Command Option 2', 23, 91);
INSERT INTO "gui_elements" VALUES (14, 'axbuttonbuttonsafaribookmarks', '', 'Safari', 'com.apple.Safari', 'Show All Bookmarks', '', 'Bookmarks', 'Command Option B', 23, 146);
INSERT INTO "gui_elements" VALUES (15, 'axbuttonbuttonsafaribookmarksbar', '', 'Safari', 'com.apple.Safari', 'Hide Bookmarks Bar', 'Show/Hide Bookmarks Bar', 'View', 'Command Shift B', 23, 140);
INSERT INTO "gui_elements" VALUES (16, 'axbuttonbuttonsafarizoomoutzoomout', '', 'Safari', 'com.apple.Safari', 'Zoom Out', 'Zoom out', 'View', 'Command -', 23, 42);
INSERT INTO "gui_elements" VALUES (17, 'axbuttonbuttonsafarizoominzoomin', '', 'Safari', 'com.apple.Safari', 'Zoom In', 'Zoom in', 'View', 'Command +', 23, 41);
INSERT INTO "gui_elements" VALUES (18, 'axbuttonbuttonsafarimail', '', 'Safari', 'com.apple.Safari', 'Email Link to this Page', '', 'Share', 'Command Shift I', 23, 130);
INSERT INTO "gui_elements" VALUES (19, 'axbuttonbuttonsafariprint', '', 'Safari', 'com.apple.Safari', 'Print…', '', 'File', 'Command P', 23, 22);
INSERT INTO "gui_elements" VALUES (20, 'axbuttonbuttonsafariwebinspector', '', 'Safari', 'com.apple.Safari', 'Show Web Inspector', 'Show/Hide Web Inspector', 'Develop', 'Command Option I', 23, 71);
INSERT INTO "gui_elements" VALUES (21, 'axbuttonbuttonsafaridownloads', '', 'Safari', 'com.apple.Safari', 'Show Downloads', '', 'View', 'Command Option L', 23, 123);
INSERT INTO "gui_elements" VALUES (22, 'axbuttonbuttonsafari1password1password', '', 'Safari', 'com.apple.Safari', '1Password', '1Password', 'View', 'Command \', 23, 211);
INSERT INTO "gui_elements" VALUES (23, 'axbuttonbuttonsafaribackshowthepreviouspage', '', 'Safari', 'com.apple.Safari', 'Back', 'Show the previous page', 'History', 'Command [', 23, 144);
INSERT INTO "gui_elements" VALUES (24, 'axbuttonbuttonsafariforwardshowthenextpage', '', 'Safari', 'com.apple.Safari', 'Forward', 'Show the next page', 'History', 'Command ]', 23, 145);
INSERT INTO "gui_elements" VALUES (25, 'axcheckboxcheckboxsafarishowreadinglistshowreadinglist', '', 'Safari', 'com.apple.Safari', 'Show Reading List', 'Show Reading List', 'View', 'Command Shift L', 23, 11);
INSERT INTO "gui_elements" VALUES (26, 'axcheckboxcheckboxsafarihidereadinglisthidereadinglist', '', 'Safari', 'com.apple.Safari', 'Hide Reading List', 'Hide Reading List', 'View', 'Command Shift L', 23, 11);
INSERT INTO "gui_elements" VALUES (27, 'axcheckboxcheckboxsafarishowbookmarksshowallbookmarks', 'axcheckboxcheckboxshowbookmarks_ns:25', 'Safari', 'com.apple.Safari', 'Show All Bookmarks', 'Show all bookmarks', 'Bookmarks', 'Command Option B', 23, 146);
INSERT INTO "gui_elements" VALUES (28, 'axcheckboxcheckboxsafarihidebookmarkshideallbookmarks', '', 'Safari', 'com.apple.Safari', 'Hide All Bookmarks', 'Hide all bookmarks', 'Bookmarks', 'Command Option B', 23, 146);
INSERT INTO "gui_elements" VALUES (29, 'axbuttonbuttonsafarishowtopsitesshowtopsites', '', 'Safari', 'com.apple.Safari', 'Show Top Sites', 'Show Top Sites', 'History', 'Command Option 1', 23, 90);
INSERT INTO "gui_elements" VALUES (31, 'axbuttonbuttonsafarishowalltabsshowalltabs', '', 'Safari', 'com.apple.Safari', 'Show All Tabs', 'Show all tabs', 'View', 'Command Shift \', 23, 214);
INSERT INTO "gui_elements" VALUES (32, 'axbuttonclosebuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Close Window', '', 'File', 'Command Shift W', 17, 131);
INSERT INTO "gui_elements" VALUES (33, 'axbuttonminimizebuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Minimize', '', 'Window', 'Command M', 17, 52);
INSERT INTO "gui_elements" VALUES (34, 'axbuttonfullscreenbuttonchrome', '', 'Chrome', 'com.google.Chrome', 'Enter Full Screen', '', 'Window', 'Command Control F', 17, 82);
INSERT INTO "gui_elements" VALUES (35, 'axbuttonbuttonchromenewtabnewtab', 'axbuttonbutton_ns:20', 'Chrome', 'com.google.Chrome', 'New Tab', 'New tab', 'File', 'Command T', 17, 37);
INSERT INTO "gui_elements" VALUES (36, 'axbuttonbuttonchromeclose', 'axbuttonbuttonclose_ns:10', 'Chrome', 'com.google.Chrome', 'Close Tab', '', 'File', 'Command W', 17, 17);
INSERT INTO "gui_elements" VALUES (37, 'axbuttonbuttonchromebackclicktogoback,holdtoseehistory', 'axbuttonbuttonback_ns:10', 'Chrome', 'com.google.Chrome', 'Back', 'Click to go back, hold to see history', 'History', 'Command [', 17, 144);
INSERT INTO "gui_elements" VALUES (38, 'axbuttonbuttonchromeforwardclicktogoforward,holdtoseehistory', 'axbuttonbuttonforward_ns:32', 'Chrome', 'com.google.Chrome', 'Forward', 'Click to go forward, hold to see history', 'History', 'Command ]', 17, 145);
INSERT INTO "gui_elements" VALUES (39, 'axbuttonbuttonchromehomeopenthehomepage', 'axbuttonbuttonhome_ns:37', 'Chrome', 'com.google.Chrome', 'Home', 'Open the home page', 'History', 'Command Shift H', 17, 124);
INSERT INTO "gui_elements" VALUES (40, 'axbuttonbuttonchromereloadreloadthispage', 'axbuttonbuttonreload_ns:63', 'Chrome', 'com.google.Chrome', 'Reload Page', 'Reload this page', 'View', 'Command R', 17, 56);
INSERT INTO "gui_elements" VALUES (41, 'axbuttonbuttonchromereloadstoploadingthispage', '', 'Chrome', 'com.google.Chrome', 'Stop', 'Stop loading this page', 'View', 'Command .', 17, 141);
INSERT INTO "gui_elements" VALUES (42, 'axtextfieldtextfieldchromeaddress', 'axtextfieldtextfieldaddress_ns:44', 'Chrome', 'com.google.Chrome', 'Open Location…', '', 'File', 'Command L', 17, 74);
INSERT INTO "gui_elements" VALUES (43, 'axbuttonbuttonchrome1password1password', '', 'Chrome', 'com.google.Chrome', '1Password', '1Password', 'View', 'Command \', 17, 211);
INSERT INTO "gui_elements" VALUES (44, 'axbuttonclosebuttonfinder', '', 'Finder', 'com.apple.finder', 'Close Window', '', 'File', 'Command W', 11, 17);
INSERT INTO "gui_elements" VALUES (45, 'axbuttonminimizebuttonfinder', '', 'Finder', 'com.apple.finder', 'Minimize', '', 'Window', 'Command M', 11, 52);
INSERT INTO "gui_elements" VALUES (46, 'axbuttonbuttonfindernewfoldercreateanewfolderinthecurrentlocation', '', 'Finder', 'com.apple.finder', 'New Folder', 'Create a new folder in the current location', 'File', 'Command Shift N', 11, 66);
INSERT INTO "gui_elements" VALUES (47, 'axbuttonbuttonfinderdeletemovetheselecteditemtothetrash', '', 'Finder', 'com.apple.finder', 'Move to Trash', 'Move the selected item to the Trash', 'File', 'Command Delete', 11, 78);
INSERT INTO "gui_elements" VALUES (48, 'axbuttonbuttonfinderconnectconnecttoaserver', '', 'Finder', 'com.apple.finder', 'Connect to Server', 'Connect to a server', 'Go', 'Command K', 11, 63);
INSERT INTO "gui_elements" VALUES (49, 'axbuttonbuttonfinderquicklookshowitemswithquicklookorasaninstantslideshow', '', 'Finder', 'com.apple.finder', 'Quick Look', 'Show items with Quick Look or as an instant slideshow', 'File', 'Command Y', 11, 75);
INSERT INTO "gui_elements" VALUES (50, 'axbuttonbuttonfindergetinfoseeinformationabouttheselectedfilesandfolders', '', 'Finder', 'com.apple.finder', 'Get Info', 'See information about the selected files and folders', 'File', 'Command I', 11, 39);
INSERT INTO "gui_elements" VALUES (51, 'axradiobuttonradiobuttonfindericonview', '', 'Finder', 'com.apple.finder', 'as Icons', '', 'View', 'Command 1', 11, 86);
INSERT INTO "gui_elements" VALUES (52, 'axradiobuttonradiobuttonfinderlistview', '', 'Finder', 'com.apple.finder', 'as List', '', 'View', 'Command 2', 11, 87);
INSERT INTO "gui_elements" VALUES (53, 'axradiobuttonradiobuttonfindercolumnview', '', 'Finder', 'com.apple.finder', 'as Columns', '', 'View', 'Command 3', 11, 88);
INSERT INTO "gui_elements" VALUES (54, 'axradiobuttonradiobuttonfindercoverflowview', '', 'Finder', 'com.apple.finder', 'as Cover Flow', '', 'View', 'Command 4', 11, 89);
INSERT INTO "gui_elements" VALUES (55, 'axbuttonbuttonfinderback', '', 'Finder', 'com.apple.finder', 'Back', '', 'Go', 'Command [', 11, 144);
INSERT INTO "gui_elements" VALUES (56, 'axbuttonbuttonfinderforward', '', 'Finder', 'com.apple.finder', 'Forward', '', 'Go', 'Command ]', 11, 145);
INSERT INTO "gui_elements" VALUES (57, 'axbuttonbuttonfinderejectejectdisksandunmountservers', '', 'Finder', 'com.apple.finder', 'Eject', 'Eject disks and unmount servers', 'File', 'Command E', 11, 32);
INSERT INTO "gui_elements" VALUES (58, 'axtextfieldsearchtextfieldfindersearchaxsearchfield', 'axtextfieldsearchtextfieldsearch_ns:125', 'Finder', 'com.apple.finder', 'Find', '', 'File', 'Command F', 11, 29);
INSERT INTO "gui_elements" VALUES (59, 'axbuttonbuttonsafarifindprevious', '', 'Safari', 'com.apple.Safari', 'Find Previous', '', 'File', 'Command Shift G', 23, 31);
INSERT INTO "gui_elements" VALUES (60, 'axbuttonbuttonsafarifindnext', '', 'Safari', 'com.apple.Safari', 'Find Next', '', 'Find', 'Command G', 23, 30);
INSERT INTO "gui_elements" VALUES (61, 'axstatictexttextfinderallmyfilesallmyfiles', '', 'Finder', 'com.apple.finder', 'All My Files', '', 'Go', 'Command Shift F', 11, 120);
INSERT INTO "gui_elements" VALUES (62, 'axstatictexttextfinderairdropairdrop', '', 'Finder', 'com.apple.finder', 'AirDrop', '', 'Go', 'Command Shift R', 11, 125);
INSERT INTO "gui_elements" VALUES (63, 'axstatictexttextfinderdesktopdesktop', '', 'Finder', 'com.apple.finder', 'Desktop', '', 'Go', 'Command Shift D', 11, 122);
INSERT INTO "gui_elements" VALUES (64, 'axstatictexttextfinderhomehome', '', 'Finder', 'com.apple.finder', 'Home', '', 'Go', 'Command Shift H', 11, 124);
INSERT INTO "gui_elements" VALUES (65, 'axstatictexttextfinderdocumentsdocuments', '', 'Finder', 'com.apple.finder', 'Documents', '', 'Go', 'Command Shift O', 11, 121);
INSERT INTO "gui_elements" VALUES (66, 'axstatictexttextfinderdownloadsdownloads', '', 'Finder', 'com.apple.finder', 'Downloads', '', 'Go', 'Command Option L', 11, 123);
INSERT INTO "gui_elements" VALUES (67, 'axstatictexttextfinderapplicationsapplications', '', 'Finder', 'com.apple.finder', 'Applications', '', 'Go', 'Command Shift A', 11, 127);
INSERT INTO "gui_elements" VALUES (68, 'axbuttonclosebuttonmail', '', 'Mail', 'com.apple.mail', 'Close All Windows', '', 'File', 'Command Option W', 19, 18);
INSERT INTO "gui_elements" VALUES (69, 'axbuttonminimizebuttonmail', '', 'Mail', 'com.apple.mail', 'Minimize', '', 'Window', 'Command M', 19, 52);
INSERT INTO "gui_elements" VALUES (70, 'axbuttonfullscreenbuttonmail', '', 'Mail', 'com.apple.mail', 'Enter Full Screen', '', 'Window', 'Command Control F', 19, 82);
INSERT INTO "gui_elements" VALUES (71, 'axbuttonbuttonmailgetmail', '', 'Mail', 'com.apple.mail', 'Get All New Mail', '', 'Mailbox', 'Command Shift N', 19, 66);
INSERT INTO "gui_elements" VALUES (72, 'axbuttonbuttonmaildeletedeleteselectedmessages', '', 'Mail', 'com.apple.mail', 'Delete', 'Delete selected messages', 'File', 'Command Delete', 19, 78);
INSERT INTO "gui_elements" VALUES (73, 'axbuttonbuttonmailjunkmarkselectedmessagesasjunk', '', 'Mail', 'com.apple.mail', 'As Junk Mail', 'Mark selected messages as Junk', 'Mark', 'Command Shift U', 19, 128);
INSERT INTO "gui_elements" VALUES (74, 'axbuttonbuttonmailjunkmarkselectedmessagesasnotjunk', '', 'Mail', 'com.apple.mail', 'As Not Junk', 'Mark selected messages as Not Junk', 'Mark', 'Command Shift U', 19, 128);
INSERT INTO "gui_elements" VALUES (75, 'axbuttonbuttonmailreplyreplytosenderofselectedmessage', '', 'Mail', 'com.apple.mail', 'Reply', 'Reply to sender of selected message', 'Message', 'Command R', 19, 56);
INSERT INTO "gui_elements" VALUES (76, 'axbuttonbuttonmailreplyallreplytoallrecipientsoftheselectedmessage', '', 'Mail', 'com.apple.mail', 'Reply All', 'Reply to all recipients of the selected message', 'Message', 'Command Shift R', 19, 125);
INSERT INTO "gui_elements" VALUES (77, 'axbuttonbuttonmailforwardforwardselectedmessages', '', 'Mail', 'com.apple.mail', 'Forward', 'Forward selected messages', 'Message', 'Command Shift F', 19, 120);
INSERT INTO "gui_elements" VALUES (78, 'axbuttonbuttonmailflagred', '', 'Mail', 'com.apple.mail', 'Red', 'Flag Red', 'Flag', 'Command Shift L', 19, 11);
INSERT INTO "gui_elements" VALUES (79, 'axbuttonbuttonmailunflagred', '', 'Mail', 'com.apple.mail', 'Red', 'Unflag Red', 'Flag', 'Command Shift L', 19, 11);
INSERT INTO "gui_elements" VALUES (80, 'axbuttonbuttonmailarchive', '', 'Mail', 'com.apple.mail', 'Archive', '', 'Message', 'Command Control A', 19, 153);
INSERT INTO "gui_elements" VALUES (81, 'axbuttonbuttonmailnewmessage', '', 'Mail', 'com.apple.mail', 'New Message', '', 'File', 'Command N', 19, 15);
INSERT INTO "gui_elements" VALUES (82, 'axbuttonbuttonmailsidebar', '', 'Mail', 'com.apple.mail', 'Show/Hide Mailbox List', '', 'View', 'Command Shift M', 19, 135);
INSERT INTO "gui_elements" VALUES (83, 'axbuttonbuttonmailprint', '', 'Mail', 'com.apple.mail', 'Print…', '', 'File', 'Command P', 19, 22);
INSERT INTO "gui_elements" VALUES (84, 'axbuttonbuttonmailunreadmarkselectedmessagesasunread', '', 'Mail', 'com.apple.mail', 'As Unread', 'Mark selected messages as unread', 'Mark', 'Command Shift U', 19, 128);
INSERT INTO "gui_elements" VALUES (85, 'axbuttonbuttonmailreadmarkselectedmessagesasread', '', 'Mail', 'com.apple.mail', 'As Read', 'Mark selected messages as read', 'Mark', 'Command Shift U', 19, 128);
INSERT INTO "gui_elements" VALUES (86, 'axbuttonbuttonmailaddress', '', 'Mail', 'com.apple.mail', 'Address Panel', '', 'Window', 'Command Option A', 19, 85);
INSERT INTO "gui_elements" VALUES (87, 'axbuttonbuttonmailaddsender', '', 'Mail', 'com.apple.mail', 'Add Sender to Contacts', '', 'Message', 'Command Shift Y', 19, 9);
INSERT INTO "gui_elements" VALUES (88, 'axtextfieldsearchtextfieldmailsearchaxsearchfield', '', 'Mail', 'com.apple.mail', 'Mailbox Search', '', 'Find', 'Command Option F', 19, 83);
INSERT INTO "gui_elements" VALUES (89, 'axbuttonbuttonmailhidemailboxlisthide', '', 'Mail', 'com.apple.mail', 'Hide Mailbox List', '', 'View', 'Command Shift M', 19, 135);
INSERT INTO "gui_elements" VALUES (90, 'axbuttonbuttonmailshowmailboxlistshow', '', 'Mail', 'com.apple.mail', 'Show Mailbox List', '', 'View', 'Command Shift M', 19, 135);
INSERT INTO "gui_elements" VALUES (91, 'axcheckboxcheckboxmailinbox', '', 'Mail', 'com.apple.mail', 'Inbox', '', 'Go to Favorite Mailbox', 'Command 1', 19, 86);
INSERT INTO "gui_elements" VALUES (92, 'axcheckboxcheckboxmailsent', '', 'Mail', 'com.apple.mail', 'Sent', '', 'Go to Favorite Mailbox', 'Command 2', 19, 87);
INSERT INTO "gui_elements" VALUES (93, 'axcheckboxcheckboxmailflagged', '', 'Mail', 'com.apple.mail', 'Flagged', '', 'Go to Favorite Mailbox', 'Command 3', 19, 88);
INSERT INTO "gui_elements" VALUES (97, 'axtextfieldtextfieldmailmailboxinboxinbox', '', 'Mail', 'com.apple.mail', 'Inbox', '', 'Go to Favorite Mailbox', 'Command 1', 19, 86);
INSERT INTO "gui_elements" VALUES (98, 'axtextfieldtextfieldmailmailboxsentsent', '', 'Mail', 'com.apple.mail', 'Sent Mail', '', 'Go to Favorite Mailbox', 'Command 2', 19, 87);
INSERT INTO "gui_elements" VALUES (99, 'axtextfieldtextfieldmailmailboxflaggedflagged', '', 'Mail', 'com.apple.mail', 'Flagged', '', 'Go to Favorite Mailbox', 'Command 3', 19, 88);
INSERT INTO "gui_elements" VALUES (100, 'axbuttonminimizebuttoncalendar', '', 'Calendar', 'com.apple.iCal', 'Minimize', '', 'Window', 'Command M', 27, 52);
INSERT INTO "gui_elements" VALUES (101, 'axbuttonfullscreenbuttoncalendar', '', 'Calendar', 'com.apple.iCal', 'Enter Full Screen', '', 'Window', 'Command Control F', 27, 82);
INSERT INTO "gui_elements" VALUES (102, 'axbuttonbuttoncalendaraddevent', '', 'Calendar', 'com.apple.iCal', 'New Event', '', 'File', 'Command N', 27, 15);
INSERT INTO "gui_elements" VALUES (103, 'axradiobuttonradiobuttoncalendarday', '', 'Calendar', 'com.apple.iCal', 'By Day', '', 'View', 'Command 1', 27, 86);
INSERT INTO "gui_elements" VALUES (104, 'axradiobuttonradiobuttoncalendarweek', '', 'Calendar', 'com.apple.iCal', 'By Week', '', 'View', 'Command 2', 27, 87);
INSERT INTO "gui_elements" VALUES (105, 'axradiobuttonradiobuttoncalendarmonth', '', 'Calendar', 'com.apple.iCal', 'By Month', '', 'View', 'Command 3', 27, 88);
INSERT INTO "gui_elements" VALUES (106, 'axtoolbarnotimplementedcalendar', '', 'Calendar', 'com.apple.iCal', 'By Year', '', 'View', 'Command 4', 27, 89);
INSERT INTO "gui_elements" VALUES (107, 'axtextfieldsearchtextfieldcalendarsearchfieldaxsearchfield', 'axtextfieldsearchtextfieldsearchfield_ns:32', 'Calendar', 'com.apple.iCal', 'Find', '', 'File', 'Command F', 27, 29);
INSERT INTO "gui_elements" VALUES (108, 'axbuttonbuttoncalendarpreviousyear', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 27, 246);
INSERT INTO "gui_elements" VALUES (109, 'axbuttonbuttoncalendarpreviousmonth', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 27, 246);
INSERT INTO "gui_elements" VALUES (110, 'axbuttonbuttoncalendarpreviousweek', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 27, 246);
INSERT INTO "gui_elements" VALUES (111, 'axbuttonbuttoncalendarpreviousday', '', 'Calendar', 'com.apple.iCal', 'Previous', '', 'View', 'Command Left Arrow', 27, 246);
INSERT INTO "gui_elements" VALUES (112, 'axbuttonbuttoncalendarnextday', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 27, 245);
INSERT INTO "gui_elements" VALUES (113, 'axbuttonbuttoncalendarnextweek', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 27, 245);
INSERT INTO "gui_elements" VALUES (114, 'axbuttonbuttoncalendarnextmonth', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 27, 245);
INSERT INTO "gui_elements" VALUES (115, 'axbuttonbuttoncalendarnextyear', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command Right Arrow', 27, 245);
INSERT INTO "gui_elements" VALUES (116, 'axbuttonbuttoncalendartoday', '', 'Calendar', 'com.apple.iCal', 'Next', '', 'View', 'Command T', 27, 37);
INSERT INTO "gui_elements" VALUES (117, 'axbuttonbuttonmailsend', '', 'Mail', 'com.apple.mail', 'Send', '', 'Message', 'Command Shift D', 19, 122);
INSERT INTO "gui_elements" VALUES (118, 'axbuttonbuttonmailattach', '', 'Mail', 'com.apple.mail', 'Attach Files…', '', 'File', 'Command Shift A', 19, 127);
INSERT INTO "gui_elements" VALUES (119, 'axcheckboxcheckboxmailboldboldtext', '', 'Mail', 'com.apple.mail', 'Bold', 'Bold text', 'Style', 'Command B', 19, 38);
INSERT INTO "gui_elements" VALUES (120, 'axcheckboxcheckboxmailmaketextitalic', '', 'Mail', 'com.apple.mail', 'Italic', 'Make text italic', 'Style', 'Command I', 19, 39);
INSERT INTO "gui_elements" VALUES (121, 'axcheckboxcheckboxmailunderlinemaketextunderlined', '', 'Mail', 'com.apple.mail', 'Underline', 'Make text underlined', 'Style', 'Command U', 19, 40);
INSERT INTO "gui_elements" VALUES (122, 'axbuttonbuttonmailaligntexttotheleft', '', 'Mail', 'com.apple.mail', 'Align Left', 'Align text to the left', 'Alignment', 'Command {', 19, 46);
INSERT INTO "gui_elements" VALUES (123, 'axbuttonbuttonmailcentertext', '', 'Mail', 'com.apple.mail', 'Center ', 'Center text', 'Alignment', 'Command |', 19, 47);
INSERT INTO "gui_elements" VALUES (124, 'axbuttonbuttonmailaligntexttotheright', '', 'Mail', 'com.apple.mail', 'Align Right', 'Align text to the right', 'Alignment', 'Command }', 19, 48);
INSERT INTO "gui_elements" VALUES (125, 'axstatictexttextmailtogo210@googlemailcomtogo210@googlemailcom', '', 'Mail', 'com.apple.mail', 'Align Right', '', 'Alignment', 'Command }', 19, 48);
INSERT INTO "gui_elements" VALUES (126, 'axbuttonbuttonmailreplyall', '', 'Mail', 'com.apple.mail', 'Reply All', 'Switch Reply to all(Command Shift R) or one(Command R) person', 'Message', 'Command R', 19, 56);
INSERT INTO "gui_elements" VALUES (127, 'axbuttonbuttonsafariaddbookmark', '', 'Safari', 'com.apple.Safari', 'Add Bookmark…', '', 'Bookmarks', 'Command D', 23, 62);
INSERT INTO "gui_elements" VALUES (128, 'axbuttonbuttonsafariautofill', '', 'Safari', 'com.apple.Safari', 'AutoFill Form', '', 'Edit', 'Command Shift A', 23, 127);
INSERT INTO "gui_elements" VALUES (130, 'axbuttonbuttonsafarinewtabcreateanewtab', '', 'Safari', 'com.apple.Safari', 'New Tab', 'Create a new tab', 'File', 'Command T', 23, 37);
INSERT INTO "gui_elements" VALUES (131, 'axstatictexttextfinderprogrammeprogramme', '', 'Finder', 'com.apple.finder', 'In den Papierkorb legen', '', 'Gehe zu', 'Command Shift A', 11, 127);
INSERT INTO "gui_elements" VALUES (132, 'axstatictexttextfinderallemeinedateienallemeinedateien', '', 'Finder', 'com.apple.finder', 'Alle meine Dateien', '', 'Gehe zu', 'Command Shift F', 11, 120);
INSERT INTO "gui_elements" VALUES (133, 'axstatictexttextfinderschreibtischschreibtisch', '', 'Finder', 'com.apple.finder', 'Schreibtisch', '', 'Gehe zu', 'Command Shift D', 11, 122);
INSERT INTO "gui_elements" VALUES (134, 'axstatictexttextfinderbenutzerordnerbenutzerordner', '', 'Finder', 'com.apple.finder', 'Benutzerordner', '', 'Gehe zu', 'Command Shift H', 11, 124);
INSERT INTO "gui_elements" VALUES (135, 'axstatictexttextfinderdokumentedokumente', '', 'Finder', 'com.apple.finder', 'Dokumente', '', 'Gehe zu', 'Command Shift O', 11, 121);
INSERT INTO "gui_elements" VALUES (136, 'axbuttonschließen-tastefinder', '', 'Finder', 'com.apple.finder', 'Schließen', '', 'Ablage', 'Command W', 11, 17);
INSERT INTO "gui_elements" VALUES (137, 'axbuttontastezumminimierenfinder', '', 'Finder', 'com.apple.finder', 'Im Dock ablegen', '', 'Fenster', 'Command M', 11, 52);
INSERT INTO "gui_elements" VALUES (138, 'axbuttontastefinderneuerordnererstellensieeinenneuenordneramaktuellenort', '', 'Finder', 'com.apple.finder', 'Neuer Ordner', 'Erstellen Sie einen neuen Ordner am aktuellen Ort', 'Ablage', 'Command Shift N', 11, 66);
INSERT INTO "gui_elements" VALUES (139, 'axbuttontastefinderlöschenausgewähltesobjektindenpapierkorblegen', '', 'Finder', 'com.apple.finder', 'In den Papierkorb legen', 'Ausgewähltes Objekt in den Papierkorb legen', 'Ablage', 'Command Delete', 11, 78);
INSERT INTO "gui_elements" VALUES (140, 'axbuttontastefinderverbindenmiteinemserververbinden', '', 'Finder', 'com.apple.finder', 'Mit Server verbinden …', 'Mit einem Server verbinden', 'Gehe zu', 'Command K', 11, 63);
INSERT INTO "gui_elements" VALUES (141, 'axbuttontastefinderübersichtobjektemit„übersicht“oderalssofortigediashowanzeigen', '', 'Finder', 'com.apple.finder', 'Übersicht', 'Objekte mit „Übersicht“ oder als sofortige Diashow anzeigen', 'Ablage', 'Command Y', 11, 75);
INSERT INTO "gui_elements" VALUES (142, 'axbuttontastefinderinformationeninformationenüberdieausgewähltendateienundordnereinblenden', '', 'Finder', 'com.apple.finder', 'Informationen', 'Informationen über die ausgewählten Dateien und Ordner einblenden', 'Ablage', 'Command I', 11, 39);
INSERT INTO "gui_elements" VALUES (143, 'axradiobuttonoptionsschaltflächefindersymboldarstellung', '', 'Finder', 'com.apple.finder', 'Als Symbole', '', 'Darstellung', 'Command 1', 11, 86);
INSERT INTO "gui_elements" VALUES (144, 'axradiobuttonoptionsschaltflächefinderlistendarstellung', '', 'Finder', 'com.apple.finder', 'Als Liste', '', 'Darstellung', 'Command 2', 11, 87);
INSERT INTO "gui_elements" VALUES (145, 'axradiobuttonoptionsschaltflächefinderspaltendarstellung', '', 'Finder', 'com.apple.finder', 'Als Spalten', '', 'Darstellung', 'Command 3', 11, 88);
INSERT INTO "gui_elements" VALUES (146, 'axradiobuttonoptionsschaltflächefindercoverflowdarstellung', '', 'Finder', 'com.apple.finder', 'Als Cover Flow', '', 'Darstellung', 'Command 4', 11, 89);
INSERT INTO "gui_elements" VALUES (147, 'axbuttontastefinderzurück', '', 'Finder', 'com.apple.finder', 'Zurück', '', 'Gehe zu', 'Command Ö', 11, 112);
INSERT INTO "gui_elements" VALUES (148, 'axbuttontastefinderweiter', '', 'Finder', 'com.apple.finder', 'Vorwärts', '', 'Gehe zu', 'Command Ä', 11, 113);
INSERT INTO "gui_elements" VALUES (149, 'axbuttontastefinderauswerfenwechselmedienauswerfenundvonserverntrennen', '', 'Finder', 'com.apple.finder', 'Auswerfen', 'Wechselmedien auswerfen und von Servern trennen', 'Ablage', 'Command E', 11, 32);
INSERT INTO "gui_elements" VALUES (150, 'axtextfieldfeldfürsuchtextfindersuchenaxsearchfield', 'axtextfieldfeldfürsuchtextsuchen_ns:120', 'Finder', 'com.apple.finder', 'Suchen', '', 'Ablage', 'Command F', 11, 29);
INSERT INTO "gui_elements" VALUES (151, 'axbuttonschließen-tastechrome', '', 'Chrome', 'com.google.Chrome', 'Fenster schließen', '', 'Ablage', 'Command Shift W', 17, 131);
INSERT INTO "gui_elements" VALUES (152, 'axbuttontastezumminimierenchrome', '', 'Chrome', 'com.google.Chrome', 'Minimieren', '', 'Fenster', 'Command M', 17, 52);
INSERT INTO "gui_elements" VALUES (153, 'axbuttontastechromeneuertabneuertab', 'axbuttontasteneuertab_ns:20', 'Chrome', 'com.google.Chrome', 'Neuer Tab', 'Neuer Tab', 'Ablage', 'Command T', 17, 37);
INSERT INTO "gui_elements" VALUES (154, 'axbuttontastechromeschließen', 'axbuttontasteschließen_ns:10', 'Chrome', 'com.google.Chrome', 'Tab schließen', '', 'Ablage', 'Command W', 17, 17);
INSERT INTO "gui_elements" VALUES (155, 'axbuttontaste„vollbildmodus“chrome', '', 'Chrome', 'com.google.Chrome', 'Vollbildmodus ein', '', 'Anzeigen', 'Command Control F', 17, 82);
INSERT INTO "gui_elements" VALUES (156, 'axbuttontastechromezurückklicken,umzurückzugehen.gedrückthalten,umverlaufaufzurufen', 'axbuttontastezurück_ns:10', 'Chrome', 'com.google.Chrome', 'Zurück', 'Klicken, um zurückzugehen. Gedrückt halten, um Verlauf aufzurufen', 'Verlauf', 'Command [', 17, 144);
INSERT INTO "gui_elements" VALUES (157, 'axbuttontastechromevorwärtsklicken,umweiterzugehen.gedrückthalten,umverlaufaufzurufen', 'axbuttontastevorwärts_ns:32', 'Chrome', 'com.google.Chrome', 'Vorwärts', 'Klicken, um weiterzugehen. Gedrückt halten, um Verlauf aufzurufen', 'Verlauf', 'Command ]', 17, 145);
INSERT INTO "gui_elements" VALUES (158, 'axbuttontastechromeneuladendieseseiteneuladen', '', 'Chrome', 'com.google.Chrome', 'Stopp', 'Seite nicht weiter laden', 'Anzeigen', 'Command .', 17, 141);
INSERT INTO "gui_elements" VALUES (159, 'axbuttontastechromeneuladenseitenichtweiterladen', '', 'Chrome', 'com.google.Chrome', 'Diese Seite neu laden', 'Diese Seite neu laden', 'Anzeigen', 'Command R', 17, 56);
INSERT INTO "gui_elements" VALUES (160, 'axbuttontastechromestartseitestartseiteöffnen', 'axbuttontastestartseite_ns:37', 'Chrome', 'com.google.Chrome', 'Startseite', 'Startseite öffnen', 'Anzeigen', 'Command Shift H', 17, 124);
INSERT INTO "gui_elements" VALUES (161, 'axtextfieldtextfeldchromeadresse', 'axtextfieldtextfeldadresse_ns:44', 'Chrome', 'com.google.Chrome', 'Adresse öffnen…', '', 'Ablage', 'Command L', 17, 74);
INSERT INTO "gui_elements" VALUES (162, 'axbuttontastechrome1password1password', '', 'Chrome', 'com.google.Chrome', '1Password', '1Password', 'Anzeigen', 'Command \', 17, 211);
INSERT INTO "gui_elements" VALUES (163, 'axbuttonschließen-tastecalendar', '', 'Calendar', 'com.apple.iCal', 'Schließen', '', 'Ablage', 'Command W', 27, 17);
INSERT INTO "gui_elements" VALUES (164, 'axbuttontastezumminimierencalendar', '', 'Calendar', 'com.apple.iCal', 'Im Dock ablegen', '', 'Fenster', 'Command M', NULL, NULL);
INSERT INTO "gui_elements" VALUES (165, 'axbuttontastecalendarereignishinzufügen', '', 'Calendar', 'com.apple.iCal', 'Neues Ereignis', '', 'Ablage', 'Command N', NULL, NULL);
INSERT INTO "gui_elements" VALUES (166, 'axradiobuttonoptionsschaltflächecalendartag', '', 'Calendar', 'com.apple.iCal', 'Tagesansicht', '', 'Darstellung', 'Command 1', NULL, NULL);
INSERT INTO "gui_elements" VALUES (167, 'axbuttontastecalendarvorherigertag', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (168, 'axbuttontastecalendarnächstertag', '', 'Calendar', 'com.apple.iCal', 'Nächster', '', 'Darstellung', 'Command  Right Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (169, 'axradiobuttonoptionsschaltflächecalendarwoche', '', 'Calendar', 'com.apple.iCal', 'Wochenansicht', '', 'Darstellung', 'Command 2', NULL, NULL);
INSERT INTO "gui_elements" VALUES (170, 'axradiobuttonoptionsschaltflächecalendarmonat', '', 'Calendar', 'com.apple.iCal', 'Monatsansicht', '', 'Darstellung', 'Command 3', NULL, NULL);
INSERT INTO "gui_elements" VALUES (171, 'axradiobuttonoptionsschaltflächecalendarjahr', '', 'Calendar', 'com.apple.iCal', 'Jahresansicht', '', 'Darstellung', 'Command 4', NULL, NULL);
INSERT INTO "gui_elements" VALUES (172, 'axtextfieldfeldfürsuchtextcalendarsuchfeldaxsearchfield', 'axtextfieldfeldfürsuchtextsuchfeld_ns:34', 'Calendar', 'com.apple.iCal', 'Suchen', '', 'Bearbeiten', 'Command F', NULL, NULL);
INSERT INTO "gui_elements" VALUES (173, 'axbuttontastecalendarvorherigesjahr', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (174, 'axbuttontastecalendarvorherigermonat', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (175, 'axbuttontastecalendarvorherigewoche', '', 'Calendar', 'com.apple.iCal', 'Zurück', '', 'Darstellung', 'Command  Left Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (176, 'axbuttontastecalendarnächstewoche', '', 'Calendar', 'com.apple.iCal', 'Nächste', '', 'Darstellung', 'Command  Right Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (177, 'axbuttontastecalendarnächstermonat', '', 'Calendar', 'com.apple.iCal', 'Nächste', '', 'Darstellung', 'Command  Right Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (178, 'axbuttontastecalendarnächstesjahr', '', 'Calendar', 'com.apple.iCal', 'Nächste', '', 'Darstellung', 'Command  Right Arrow ', NULL, NULL);
INSERT INTO "gui_elements" VALUES (179, 'axbuttontastecalendarheute', '', 'Calendar', 'com.apple.iCal', 'Heute anzeigen', '', 'Darstellung', 'Command T', NULL, NULL);
