INSERT INTO "gui_elements" VALUES (NULL, 'axstatictexttextofinderaplicacionesaplicaciones', '', 'Finder', 'com.apple.finder', 'Aplicaciones', '', 'Ir', 'Command Shift A', 3, 98);
INSERT INTO "gui_elements" VALUES (NULL, 'axstatictexttextofindertodosmisarchivostodosmisarchivos', '', 'Finder', 'com.apple.finder', 'Todos mis archivos', '', 'Ir', 'Command Shift F', 3, 90);
INSERT INTO "gui_elements" VALUES (NULL, 'axstatictexttextofinderairdropairdrop', '', 'Finder', 'com.apple.finder', 'AirDrop', '', 'Ir', 'Command Shift R', 3, 96);
INSERT INTO "gui_elements" VALUES (NULL, 'axstatictexttextofinderescritorioescritorio', '', 'Finder', 'com.apple.finder', 'Escritorio', '', 'Ir', 'Command Shift D', 3, 92);
INSERT INTO "gui_elements" VALUES (NULL, 'axstatictexttextofinderhomehome', '', 'Finder', 'com.apple.finder', 'Home', '', 'Ir', 'Command Shift H', 3, 94);
INSERT INTO "gui_elements" VALUES (NULL, 'axstatictexttextofinderdocumentosdocumentos', '', 'Finder', 'com.apple.finder', 'Documentos', '', 'Ir', 'Command Shift O', 3, 91);
INSERT INTO "gui_elements" VALUES (NULL, 'axstatictexttextofinderdescargasdescargas', '', 'Finder', 'com.apple.finder', 'Descargas', '', 'Ir', 'Command Option L', 3, 93);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfindercarpetanuevacrearunacarpetanuevaenlaubicaciónactual', '', 'Finder', 'com.apple.finder', 'Nueva carpeta', 'Crear una carpeta nueva en la ubicación actual', 'Archivo', 'Command Shift N', 3, 17);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfindereliminartrasladarelítemseleccionadoalapapelera', '', 'Finder', 'com.apple.finder', 'Mostrar original', 'Trasladar el ítem seleccionado a la Papelera', 'Archivo', 'Command Delete', 3, 37);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfinderconectarconectarseaunservidor', '', 'Finder', 'com.apple.finder', 'Conectarse al servidor', 'Conectarse a un servidor', 'Ir', 'Command K', 3, 101);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfindervistarápidamostrarítemsconvistarápidaocomopasedediapositivasinstantáneo', '', 'Finder', 'com.apple.finder', 'Vista rápida de ', 'Mostrar ítems con Vista Rápida o como pase de diapositivas instantáneo', 'Archivo', 'Command Y', 3, 32);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfinderobtenerinformaciónmostrarlainformaciónacercadelosarchivosycarpetasseleccionados', '', 'Finder', 'com.apple.finder', 'Obtener información', 'Mostrar la información acerca de los archivos y carpetas seleccionados', 'Archivo', 'Command I', 3, 26);
INSERT INTO "gui_elements" VALUES (NULL, 'axradiobuttonbotóndeselecciónfindervisualizacióncomoiconos', '', 'Finder', 'com.apple.finder', 'Como iconos', '', 'Visualización', 'Command 1', 3, 54);
INSERT INTO "gui_elements" VALUES (NULL, 'axradiobuttonbotóndeselecciónfindervisualizacióncomocolumnas', '', 'Finder', 'com.apple.finder', 'Como columnas', '', 'Visualización', 'Command 3', 3, 56);
INSERT INTO "gui_elements" VALUES (NULL, 'axradiobuttonbotóndeselecciónfindervisualizacióncoverflow', '', 'Finder', 'com.apple.finder', 'Como Cover Flow', '', 'Visualización', 'Command 4', 3, 57);
INSERT INTO "gui_elements" VALUES (NULL, 'axradiobuttonbotóndeselecciónfindervisualizacióncomolista', '', 'Finder', 'com.apple.finder', 'Como lista', '', 'Visualización', 'Command 2', 3, 55);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfinderatrás', '', 'Finder', 'com.apple.finder', 'Atrás', '', 'Ir', 'Command Left Arrow', 3, 222);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfinderadelante', '', 'Finder', 'com.apple.finder', 'Adelante', '', 'Ir', 'Command Right Arrow', 3, 221);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotónfinderexpulsarexpulsardiscosydesmontarservidores', '', 'Finder', 'com.apple.finder', 'Expulsar', 'Expulsar discos y desmontar servidores', 'Archivo', 'Command E', 3, 39);
INSERT INTO "gui_elements" VALUES (NULL, 'axtextfieldcampodetextodebúsquedafinderbuscaraxsearchfield', 'axtextfieldcampodetextodebúsquedabuscar_ns:120', 'Finder', 'com.apple.finder', 'Buscar', '', 'Archivo', 'Command F', 3, 42);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotóndecierrefinder', '', 'Finder', 'com.apple.finder', 'Cerrar ventana', '', 'Archivo', 'Command W', 3, 24);
INSERT INTO "gui_elements" VALUES (NULL, 'axbuttonbotóndeminimizaciónfinder', '', 'Finder', 'com.apple.finder', 'Minimizar', '', 'Ventana', 'Command M', 3, 102);
